### ISSUE TITLE
openwrt on xiaomi-4a-gigabit will infinite restart

### ISSUE THREAD

**Issue by EpicDogger** [openwrt/openwrt#9652] opened 2022-04-05 15:14 UTC
<img width="559" alt="0d8e6020fdac5929242506ee14e0abc" src="https://user-images.githubusercontent.com/103055796/161786642-9a56c037-105e-4688-8549-f003f08aed75.png">
this is the router information on breed

**Comment by bill888uk** [comment] 2022-04-06 02:10
flash chip ID 1c7118 is for EN25QX128A 
https://github.com/openwrt/openwrt/issues/9442

**Comment by Ansuel** [comment] 2022-10-14 20:57
Closing this as it's a duplicate of #9442

**Closed by Ansuel** 2022-10-14 20:57 UTC
Labels: insufficient details, duplicate
