### ISSUE TITLE
build image failed

### ISSUE THREAD

**Issue by mirthlesslk** [openwrt/openwrt#13843] opened 2023-11-01 04:59 UTC
### Describe the bug

FAILED: libdwarves.so.1.0.0 
: && /workdir/openwrt/staging_dir/host/bin/gcc -fPIC -O2 -I/workdir/openwrt/staging_dir/host/include -pthread -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -O2  -L/workdir/openwrt/staging_dir/host/lib -shared -Wl,-soname,libdwarves.so.1 -o libdwarves.so.1.0.0 CMakeFiles/bpf.dir/lib/bpf/src/bpf.c.o CMakeFiles/bpf.dir/lib/bpf/src/bpf_prog_linfo.c.o CMakeFiles/bpf.dir/lib/bpf/src/btf.c.o CMakeFiles/bpf.dir/lib/bpf/src/btf_dump.c.o CMakeFiles/bpf.dir/lib/bpf/src/gen_loader.c.o CMakeFiles/bpf.dir/lib/bpf/src/hashmap.c.o CMakeFiles/bpf.dir/lib/bpf/src/libbpf.c.o CMakeFiles/bpf.dir/lib/bpf/src/libbpf_errno.c.o CMakeFiles/bpf.dir/lib/bpf/src/libbpf_probes.c.o CMakeFiles/bpf.dir/lib/bpf/src/linker.c.o CMakeFiles/bpf.dir/lib/bpf/src/netlink.c.o CMakeFiles/bpf.dir/lib/bpf/src/nlattr.c.o CMakeFiles/bpf.dir/lib/bpf/src/relo_core.c.o CMakeFiles/bpf.dir/lib/bpf/src/ringbuf.c.o CMakeFiles/bpf.dir/lib/bpf/src/str_error.c.o CMakeFiles/bpf.dir/lib/bpf/src/strset.c.o CMakeFiles/bpf.dir/lib/bpf/src/usdt.c.o CMakeFiles/dwarves.dir/dwarves.c.o CMakeFiles/dwarves.dir/dwarves_fprintf.c.o CMakeFiles/dwarves.dir/gobuffer.c.o CMakeFiles/dwarves.dir/ctf_loader.c.o CMakeFiles/dwarves.dir/libctf.c.o CMakeFiles/dwarves.dir/btf_encoder.c.o CMakeFiles/dwarves.dir/btf_loader.c.o CMakeFiles/dwarves.dir/dwarf_loader.c.o CMakeFiles/dwarves.dir/dutil.c.o CMakeFiles/dwarves.dir/elf_symtab.c.o CMakeFiles/dwarves.dir/rbtree.c.o  -Wl,-rpath,:::::::::::::::::::::::::::::::::::::  -Wl,-Bstatic  -ldw  -lelf  -lz  -Wl,-Bdynamic && :
make[3]: *** [Makefile:36: /workdir/openwrt/build_dir/host/dwarves-1.25/.built] Error 1
make[2]: *** [tools/Makefile:230: tools/dwarves/compile] Error 1
/usr/bin/ld: /workdir/openwrt/staging_dir/host/lib/libdw.a(dwarf_error.o): relocation R_X86_64_TPOFF32 against `global_error' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
make[3]: Leaving directory '/workdir/openwrt/tools/dwarves'
time: tools/dwarves/compile#9.60#0.51#10.13
    ERROR: tools/dwarves failed to build.
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [tools/Makefile:226: /workdir/openwrt/staging_dir/host/stamp/.tools_compile_nyyynyynnnyyyyynyyyyyyynyyynnnynyynnynnyyyyyynyyyyyyyyyynynynnyyyyyyy] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:232: world] Error 2
Error: Process completed with exit code 2.

### OpenWrt version

3bbc1d5fba1d700917138334a48c16bafdf48de9

### OpenWrt target/subtarget

main

### Device

a53

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by ynezz** [comment] 2023-11-01 06:28
Duplicate of #13841

**Closed by ynezz** 2023-11-01 06:28 UTC
Labels: bug
