### ISSUE TITLE
AMPDU On N mode

### ISSUE THREAD

**Issue by Svetoslav92** [openwrt/openwrt#15742] opened 2024-06-18 11:40 UTC
### Describe the bug

Opened in here and never closed https://github.com/openwrt/openwrt/issues/10761

We have the same question in here with all the details -> https://forum.openwrt.org/t/manually-setting-ampdu-on-n-mode/201419

Seems like supported routers on N mode cannot set the AMPDU or at least nobody is telling how to set the AMPDU params so far.

### OpenWrt version

17-23

### OpenWrt release

ALL

### OpenWrt target/subtarget

ALL

### Device

ALL

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by jow-** [comment] 2024-06-18 16:08
Duplicate of #10761

**Closed by jow-** 2024-06-18 16:08 UTC
Labels: bug, invalid
