### ISSUE TITLE
script/download.pl does not work when curl is missing

### ISSUE THREAD

**Issue by neheb** [openwrt/openwrt#10694] opened 2022-09-13 01:43 UTC
```
mkdir -p /home/mangix/devstuff/openwrt/dl
SHELL= flock /home/mangix/devstuff/openwrt/tmp/.xz-5.2.6.tar.bz2.flock -c '     /home/mangix/devstuff/openwrt/scripts/download.pl "/home/mangix/devstuff/openwrt/dl" "xz-5.2.6.tar.bz2" "13e3402e301b6018f6a71ef0e497f714c6d11e214ae82dab156b81c2a64acb25" "" "@SF/lzmautils" "http://tukaani.org/xz"    '
Can't exec "curl": No such file or directory at /home/mangix/devstuff/openwrt/scripts/download.pl line 77.
+ wget --tries=5 --timeout=20 --output-document=-  https://downloads.sourceforge.net/lzmautils/xz-5.2.6.tar.bz2
http://: Invalid host name.
--2022-09-13 01:37:23--  https://downloads.sourceforge.net/lzmautils/xz-5.2.6.tar.bz2
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 204.68.111.105
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|204.68.111.105|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cytranet.dl.sourceforge.net/project/lzmautils/xz-5.2.6.tar.bz2 [following]
--2022-09-13 01:37:23--  https://cytranet.dl.sourceforge.net/project/lzmautils/xz-5.2.6.tar.bz2
Resolving cytranet.dl.sourceforge.net (cytranet.dl.sourceforge.net)... 162.251.237.20
Connecting to cytranet.dl.sourceforge.net (cytranet.dl.sourceforge.net)|162.251.237.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1658182 (1.6M) [application/octet-stream]
Saving to: 'STDOUT'

-                             100%[=================================================>]   1.58M  2.35MB/s    in 0.7s

2022-09-13 01:37:24 (2.35 MB/s) - written to stdout [1658182/1658182]

FINISHED --2022-09-13 01:37:24--
Total wall clock time: 1.0s
Downloaded: 1 files, 1.6M in 0.7s (2.35 MB/s)
Download failed.
Can't exec "curl": No such file or directory at /home/mangix/devstuff/openwrt/scripts/download.pl line 77.
+ wget --tries=5 --timeout=20 --output-document=-  https://downloads.sourceforge.net/lzmautils/xz-5.2.6.tar.bz2
http://: Invalid host name.
--2022-09-13 01:37:24--  https://downloads.sourceforge.net/lzmautils/xz-5.2.6.tar.bz2
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 204.68.111.105
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|204.68.111.105|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://versaweb.dl.sourceforge.net/project/lzmautils/xz-5.2.6.tar.bz2 [following]
--2022-09-13 01:37:25--  https://versaweb.dl.sourceforge.net/project/lzmautils/xz-5.2.6.tar.bz2
Resolving versaweb.dl.sourceforge.net (versaweb.dl.sourceforge.net)... 162.251.232.173
Connecting to versaweb.dl.sourceforge.net (versaweb.dl.sourceforge.net)|162.251.232.173|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1658182 (1.6M) [application/octet-stream]
Saving to: 'STDOUT'

-                             100%[=================================================>]   1.58M  4.49MB/s    in 0.4s

2022-09-13 01:37:26 (4.49 MB/s) - written to stdout [1658182/1658182]

FINISHED --2022-09-13 01:37:26--
Total wall clock time: 1.7s
Downloaded: 1 files, 1.6M in 0.4s (4.49 MB/s)
Download failed.
Can't exec "curl": No such file or directory at /home/mangix/devstuff/openwrt/scripts/download.pl line 77.
+ wget --tries=5 --timeout=20 --output-document=-  https://downloads.sourceforge.net/lzmautils/xz-5.2.6.tar.bz2
http://: Invalid host name.
--2022-09-13 01:37:26--  https://downloads.sourceforge.net/lzmautils/xz-5.2.6.tar.bz2
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 204.68.111.105
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|204.68.111.105|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cytranet.dl.sourceforge.net/project/lzmautils/xz-5.2.6.tar.bz2 [following]
--2022-09-13 01:37:27--  https://cytranet.dl.sourceforge.net/project/lzmautils/xz-5.2.6.tar.bz2
Resolving cytranet.dl.sourceforge.net (cytranet.dl.sourceforge.net)... 162.251.237.20
Connecting to cytranet.dl.sourceforge.net (cytranet.dl.sourceforge.net)|162.251.237.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1658182 (1.6M) [application/octet-stream]
Saving to: 'STDOUT'

-                             100%[=================================================>]   1.58M  2.71MB/s    in 0.6s

2022-09-13 01:37:28 (2.71 MB/s) - written to stdout [1658182/1658182]

FINISHED --2022-09-13 01:37:28--
Total wall clock time: 2.1s
Downloaded: 1 files, 1.6M in 0.6s (2.71 MB/s)
Download failed.
Can't exec "curl": No such file or directory at /home/mangix/devstuff/openwrt/scripts/download.pl line 77.
+ wget --tries=5 --timeout=20 --output-document=-  https://downloads.sourceforge.net/lzmautils/xz-5.2.6.tar.bz2
http://: Invalid host name.
--2022-09-13 01:37:28--  https://downloads.sourceforge.net/lzmautils/xz-5.2.6.tar.bz2
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 204.68.111.105
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|204.68.111.105|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://versaweb.dl.sourceforge.net/project/lzmautils/xz-5.2.6.tar.bz2 [following]
--2022-09-13 01:37:29--  https://versaweb.dl.sourceforge.net/project/lzmautils/xz-5.2.6.tar.bz2
Resolving versaweb.dl.sourceforge.net (versaweb.dl.sourceforge.net)... 162.251.232.173
Connecting to versaweb.dl.sourceforge.net (versaweb.dl.sourceforge.net)|162.251.232.173|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1658182 (1.6M) [application/octet-stream]
Saving to: 'STDOUT'

-                             100%[=================================================>]   1.58M   888KB/s    in 1.8s

2022-09-13 01:37:31 (888 KB/s) - written to stdout [1658182/1658182]

FINISHED --2022-09-13 01:37:31--
Total wall clock time: 3.3s
Downloaded: 1 files, 1.6M in 1.8s (888 KB/s)
Download failed.
Can't exec "curl": No such file or directory at /home/mangix/devstuff/openwrt/scripts/download.pl line 77.
+ wget --tries=5 --timeout=20 --output-document=-  https://downloads.sourceforge.net/lzmautils/xz-5.2.6.tar.bz2
http://: Invalid host name.
--2022-09-13 01:37:31--  https://downloads.sourceforge.net/lzmautils/xz-5.2.6.tar.bz2
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 204.68.111.105
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|204.68.111.105|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://versaweb.dl.sourceforge.net/project/lzmautils/xz-5.2.6.tar.bz2 [following]
--2022-09-13 01:37:32--  https://versaweb.dl.sourceforge.net/project/lzmautils/xz-5.2.6.tar.bz2
Resolving versaweb.dl.sourceforge.net (versaweb.dl.sourceforge.net)... 162.251.232.173
Connecting to versaweb.dl.sourceforge.net (versaweb.dl.sourceforge.net)|162.251.232.173|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1658182 (1.6M) [application/octet-stream]
Saving to: 'STDOUT'

-                             100%[=================================================>]   1.58M  3.39MB/s    in 0.5s

2022-09-13 01:37:32 (3.39 MB/s) - written to stdout [1658182/1658182]

FINISHED --2022-09-13 01:37:32--
Total wall clock time: 0.8s
Downloaded: 1 files, 1.6M in 0.5s (3.39 MB/s)
Download failed.
Can't exec "curl": No such file or directory at /home/mangix/devstuff/openwrt/scripts/download.pl line 77.
+ wget --tries=5 --timeout=20 --output-document=-  http://tukaani.org/xz/xz-5.2.6.tar.bz2
http://: Invalid host name.
--2022-09-13 01:37:32--  http://tukaani.org/xz/xz-5.2.6.tar.bz2
Resolving tukaani.org (tukaani.org)... 84.34.147.45
Connecting to tukaani.org (tukaani.org)|84.34.147.45|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://tukaani.org/xz/xz-5.2.6.tar.bz2 [following]
--2022-09-13 01:37:33--  https://tukaani.org/xz/xz-5.2.6.tar.bz2
Connecting to tukaani.org (tukaani.org)|84.34.147.45|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://sourceforge.net/projects/lzmautils/files/xz-5.2.6.tar.bz2/download [following]
--2022-09-13 01:37:33--  https://sourceforge.net/projects/lzmautils/files/xz-5.2.6.tar.bz2/download
Resolving sourceforge.net (sourceforge.net)... 104.18.34.243, 172.64.153.13
Connecting to sourceforge.net (sourceforge.net)|104.18.34.243|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://downloads.sourceforge.net/project/lzmautils/xz-5.2.6.tar.bz2?ts=gAAAAABjH97eAAI0Rj5MNMTO02jgGVqvI_rQ-2oHqeZFUABI07W7mLVHxMsAj5lNiwWFzWlKceP5pn2m_rQTvwZjYlDWpf5sDQ%3D%3D&use_mirror=cfhcable&r= [following]
--2022-09-13 01:37:34--  https://downloads.sourceforge.net/project/lzmautils/xz-5.2.6.tar.bz2?ts=gAAAAABjH97eAAI0Rj5MNMTO02jgGVqvI_rQ-2oHqeZFUABI07W7mLVHxMsAj5lNiwWFzWlKceP5pn2m_rQTvwZjYlDWpf5sDQ%3D%3D&use_mirror=cfhcable&r=
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 204.68.111.105
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|204.68.111.105|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cfhcable.dl.sourceforge.net/project/lzmautils/xz-5.2.6.tar.bz2 [following]
--2022-09-13 01:37:34--  https://cfhcable.dl.sourceforge.net/project/lzmautils/xz-5.2.6.tar.bz2
Resolving cfhcable.dl.sourceforge.net (cfhcable.dl.sourceforge.net)... 146.71.73.6
Connecting to cfhcable.dl.sourceforge.net (cfhcable.dl.sourceforge.net)|146.71.73.6|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1658182 (1.6M) [application/octet-stream]
Saving to: 'STDOUT'

-                             100%[=================================================>]   1.58M   654KB/s    in 2.5s

2022-09-13 01:37:37 (654 KB/s) - written to stdout [1658182/1658182]

FINISHED --2022-09-13 01:37:37--
Total wall clock time: 4.5s
Downloaded: 1 files, 1.6M in 2.5s (654 KB/s)
Download failed.
Can't exec "curl": No such file or directory at /home/mangix/devstuff/openwrt/scripts/download.pl line 77.
+ wget --tries=5 --timeout=20 --output-document=-  https://sources.cdn.openwrt.org/xz-5.2.6.tar.bz2
http://: Invalid host name.
--2022-09-13 01:37:37--  https://sources.cdn.openwrt.org/xz-5.2.6.tar.bz2
Resolving sources.cdn.openwrt.org (sources.cdn.openwrt.org)... 2a04:4e42:2d::644, 151.101.42.132
Connecting to sources.cdn.openwrt.org (sources.cdn.openwrt.org)|2a04:4e42:2d::644|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1658182 (1.6M) [application/octet-stream]
Saving to: 'STDOUT'

-                             100%[=================================================>]   1.58M  6.40MB/s    in 0.2s

2022-09-13 01:37:37 (6.40 MB/s) - written to stdout [1658182/1658182]

FINISHED --2022-09-13 01:37:37--
Total wall clock time: 0.4s
Downloaded: 1 files, 1.6M in 0.2s (6.40 MB/s)
Download failed.
Can't exec "curl": No such file or directory at /home/mangix/devstuff/openwrt/scripts/download.pl line 77.
+ wget --tries=5 --timeout=20 --output-document=-  https://sources.openwrt.org/xz-5.2.6.tar.bz2
http://: Invalid host name.
--2022-09-13 01:37:37--  https://sources.openwrt.org/xz-5.2.6.tar.bz2
Resolving sources.openwrt.org (sources.openwrt.org)... 2a01:4f8:210:5087::2, 148.251.151.136
Connecting to sources.openwrt.org (sources.openwrt.org)|2a01:4f8:210:5087::2|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1658182 (1.6M) [application/octet-stream]
Saving to: 'STDOUT'

-                             100%[=================================================>]   1.58M  1.65MB/s    in 1.0s

2022-09-13 01:37:39 (1.65 MB/s) - written to stdout [1658182/1658182]

FINISHED --2022-09-13 01:37:39--
Total wall clock time: 2.0s
Downloaded: 1 files, 1.6M in 1.0s (1.65 MB/s)
Download failed.
Can't exec "curl": No such file or directory at /home/mangix/devstuff/openwrt/scripts/download.pl line 77.
+ wget --tries=5 --timeout=20 --output-document=-  https://mirror2.openwrt.org/sources/xz-5.2.6.tar.bz2
http://: Invalid host name.
--2022-09-13 01:37:39--  https://mirror2.openwrt.org/sources/xz-5.2.6.tar.bz2
Resolving mirror2.openwrt.org (mirror2.openwrt.org)... 2a01:4f8:221:3d45::2, 46.4.11.11
Connecting to mirror2.openwrt.org (mirror2.openwrt.org)|2a01:4f8:221:3d45::2|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-09-13 01:37:40 ERROR 404: Not Found.

Download failed.
No more mirrors to try - giving up.
make[3]: *** [Makefile:37: /home/mangix/devstuff/openwrt/dl/xz-5.2.6.tar.bz2] Error 2
make[3]: Leaving directory '/home/mangix/devstuff/openwrt/tools/xz'
time: tools/xz/compile#0.21#0.13#16.63
    ERROR: tools/xz failed to build.
make[2]: *** [tools/Makefile:174: tools/xz/compile] Error 1
make[2]: Leaving directory '/home/mangix/devstuff/openwrt'
make[1]: *** [tools/Makefile:170: /home/mangix/devstuff/openwrt/staging_dir/host/stamp/.tools_compile_nyyyyyynnyyyynynyyyyyyynyynnyynynyyyyyyyyyyyyyyyyynynnyyyyyyy] Error 2
make[1]: Leaving directory '/home/mangix/devstuff/openwrt'
make: *** [/home/mangix/devstuff/openwrt/include/toplevel.mk:231: world] Error 2
localhost:~/devstuff/openwrt$ wget --tries=5 --timeout=20 --output-document=-  https://mirror2.openwrt.org/sources/xz-5.2.6.tar.bz2
--2022-09-12 18:39:05--  https://mirror2.openwrt.org/sources/xz-5.2.6.tar.bz2
Resolving mirror2.openwrt.org (mirror2.openwrt.org)... 2a01:4f8:221:3d45::2, 46.4.11.11
Connecting to mirror2.openwrt.org (mirror2.openwrt.org)|2a01:4f8:221:3d45::2|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-09-12 18:39:06 ERROR 404: Not Found.

localhost:~/devstuff/openwrt$ wget --tries=5 --timeout=20 https://mirror2.openwrt.org/sources/xz-5.2.6.tar.bz2
--2022-09-12 18:39:18--  https://mirror2.openwrt.org/sources/xz-5.2.6.tar.bz2
Resolving mirror2.openwrt.org (mirror2.openwrt.org)... 2a01:4f8:221:3d45::2, 46.4.11.11
Connecting to mirror2.openwrt.org (mirror2.openwrt.org)|2a01:4f8:221:3d45::2|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-09-12 18:39:19 ERROR 404: Not Found.
```

ping @jow-

**Comment by ynezz** [comment] 2022-09-13 04:29
Duplicate of #10692

**Closed by ynezz** 2022-09-13 04:29 UTC
