### ISSUE TITLE
firewall4 cant handle xxx/yyy marks

### ISSUE THREAD

**Issue by bol-van** [openwrt/openwrt#11135] opened 2022-11-02 07:40 UTC
Openwrt 22.03.2

possible typo. this change fixes the issue :

/usr/share/firewall4/templates/rule.uc 
```
<                                               : 'mark and ' + fw4.hex(~r.set_xmark.mask & 0xFFFFFFFF) + ' xor ' + fw4.hex(r.set_xmark.mark)
---
>                                               : 'mark and ' + fw4.hex(~rule.set_xmark.mask & 0xFFFFFFFF) + ' xor ' + fw4.hex(rule.set_xmark.mark)
```

**Comment by jow-** [comment] 2022-11-02 07:46
Duplicate of #10965

**Closed by jow-** 2022-11-02 07:46 UTC
