### ISSUE TITLE
The VLAN (802.1ad) function of openwrt version 23.05.0 does not work properly.

### ISSUE THREAD

**Issue by Tonkercke** [openwrt/openwrt#13896] opened 2023-11-07 09:31 UTC
### Describe the bug

When I use the openwrt 23.05.0 system, I need to create a lan2 network interface for IP address isolation. The steps are: first add a ‘VLAN (802.1ad) ’device, select eth0 as ‘Base device’ and save it, and then create a ‘Bridge device’. ‘Bridge ports’ select the eth0.1 just created, named br-lan2, and then save it. After adding the device, go back to Interfaces to add the lan2 interface, set the interface to a static address, and set the IP address to an address different from the lan. Finally, add a WiFi signal for broadcast in the wireless settings, and set the ‘network’ in the WiFi settings to lan2. After setting up, connect to WiFi on the PC.

Under normal circumstances, the PC-side wireless network card can quickly connect and obtain the IP address of lan2, but now it has been unable to obtain the IP address after connecting to WiFi. After repeated testing, the IP address cannot be obtained, and the IP address of the PC-side wireless network card is manually set. Can't log in to the console either.

It can be used normally under the openwrt 19 and openwrt 21 versions of the system by following the above steps, but after updating to openwrt 22.03.5 and the current openwrt 23.05.0 system, it cannot be used normally.

Note: Every time I upgrade, I manually reset all system settings. After reset, I still cannot use it after following the above steps.
![01](https://github.com/openwrt/openwrt/assets/67683757/33248e37-9e9a-4b2d-b9a5-da4acdc71927)
![02](https://github.com/openwrt/openwrt/assets/67683757/4a82fb10-d423-44d7-b98f-841518d6940c)
![03](https://github.com/openwrt/openwrt/assets/67683757/cf49d5f0-bb51-4e93-8c36-3d6c10f8b527)
![04](https://github.com/openwrt/openwrt/assets/67683757/a537ae9f-601d-434e-b5fd-473a75a97d79)

### OpenWrt version

openwrt 23.05

### OpenWrt target/subtarget

openwrt 23.05.0

### Device

xiaomi R3G,Netgear r8000,ac2100

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by voxelcat** [comment] 2023-11-07 12:51
If this device got converted to DSA try this:

Don't create vlan devices yourself. Create a bridge for your physical interface (eg br-lan for eth0), if it doesn't already exist, and use the tab 'bridge vlan filtering' to configure your VLANs there. Interfaces for the individual vlan bridges (br-lan.1, etc) will appear automatically.
DSA uses vlan aware bridges.

**Comment by Tonkercke** [comment] 2023-11-07 14:25
> If this device got converted to DSA try this:
> 
> Don't create vlan devices yourself. Create a bridge for your physical interface(s) (eg br-lan for lan1,... ), if it doesn't already exist, and use the tab 'bridge vlan filtering' to configure your VLANs there. Interfaces for the individual vlan bridges will appear automatically. DSA uses vlan aware bridges.
> 
> Edit: lan1, not eth0. See here https://openwrt.org/docs/guide-user/network/dsa/dsa-mini-tutorial

Set up according to ' 2. Multiple bridged networks ' in the tutorial you provided, I set the first bridge device br-lan to the two physical ports lan1 and lan2, and set the 3rd lan physical port (lan3) to Create a new bridge device (br-office), then re-create a new interface (office), and finally set the WiFi network to the new office interface. After setting up, the PC still cannot obtain the IP address when connected to WiFi. I plugged the network cable into the lan3 interface. The PC still cannot obtain the IP address, but lan1 and lan2 under br-lan can obtain the IP address normally.

In addition, I found that the WiFi signal broadcast by the MT7603 network card device in redmi ac2100 and xiaomi R3G cannot be connected using the PC wireless network card. No matter whether the network in the WiFi settings is changed to lan or office, the connection cannot be made, or Can connect but cannot get IP address, only 5G signal, MT7612E and MT7615 can be used normally. However, the MT7603 network card can relay other wireless signals to access the Internet.
![01](https://github.com/openwrt/openwrt/assets/67683757/e497f3f4-f616-463c-a259-64c490b1811d)
![02](https://github.com/openwrt/openwrt/assets/67683757/e96208d2-87ce-4083-bdff-3a33fb275e13)
![03](https://github.com/openwrt/openwrt/assets/67683757/9246c695-e34e-4496-9f08-21fca388309e)
![04](https://github.com/openwrt/openwrt/assets/67683757/93be62b7-1f68-4211-afcf-edc47359193e)
![05](https://github.com/openwrt/openwrt/assets/67683757/92d97c5b-b9e1-4d1d-986f-bc063e207d16)

**Comment by brada4** [comment] 2023-11-07 15:00
default is input/reject forward/reject for interface (bridge on your case, not cable socket) not assigned to firewall zones.
It is under network/firewall, add new zone and add interface. Allow forwarding if/where intended.

**Comment by Tonkercke** [comment] 2023-11-07 15:26
All communication rules of the firewall are disabled, and the outbound, inbound, and forwarding in the interface have been changed to 'accept', but the IP address is still unable to be obtained.

**Comment by brada4** [comment] 2023-11-07 16:14
- check logread for dhcp requests
- check brctl that wlan is indeed in the bridge
- tcpdump on accesspoint and bridge interfaces.

**Comment by brada4** [comment] 2023-11-07 19:18
R8000 is broadcom chipset and works differently. Can you edit one you are editing here?

**Comment by Tonkercke** [comment] 2023-11-07 23:29
Running 'brctl show' displays the following information:
---------------------------------------------------------------------
root@OpenWrt:~# brctl show
bridge name     bridge id               STP enabled     interfaces
br-lan          7fff.16c2c1a1a7c1       no              lan2
                                                        lan3
                                                        lan1
br-ofiice               7fff.26a5ff334598       no              wlan1-1
------------------------------------------------------------------
wlan1-1 is my wireless network name.

**Comment by brada4** [comment] 2023-11-08 00:48
so hou claim lan3 mysteriously does not get dhcp address. Reset configuration and redo whole setup again. Something is left  from your -ad experiment. Namely lan3 in brctl does not match config, interface name wlan2-5 is from  v22.

**Comment by Tonkercke** [comment] 2023-11-08 01:14
Just now, I reset all the settings of the router and manually set up the interface, bridge, and wireless again. However, the newly created interface still cannot obtain an IP address.

I uploaded a copy of my relevant configuration files, please help me see where the problem lies.

[config.zip](https://github.com/openwrt/openwrt/files/13290905/config.zip)

**Comment by brada4** [comment] 2023-11-08 01:20
You need to connect wifi to a bridge in wifi config, not add as bridge port.

**Comment by brada4** [comment] 2023-11-08 01:23
And click empty bridge checkbox for that bridge...

**Comment by brada4** [comment] 2023-11-08 01:26
and accept input on office net, and probably allow forward to wan (see lan setup)

**Comment by Tonkercke** [comment] 2023-11-08 01:33
According to your suggestion, I can finally obtain the IP address. Thank you very much.

**Comment by brada4** [comment] 2023-11-08 01:43
you may now move physical port to the 'office' as intended in pictures. First remove from old bridge, save/apply, check brctl, then add/save  and check command again.

**Comment by Tonkercke** [comment] 2023-11-08 01:52
ok .

**Closed** 2023-11-08 01:53 UTC
Labels: bug
