### ISSUE TITLE
[Edited]TP-Link Archer C50V4 Luci exposes unsupported frequencies for 5GHz Wi-Fi & LED state mislabelled

### ISSUE THREAD

**Issue by erayrafet** [openwrt/openwrt#10663] opened 2022-09-10 10:45 UTC
As the title say, Luci shows support for 5GHz Wi-FI channels higher than 48. Sadly, the hardware doesn't support those and picking anything higher than 48 (52, 100, etc.) results in AC Wi-Fi not initializing/working.
Running version 22.03.0.

![image](https://user-images.githubusercontent.com/34194191/189479856-3f599dc4-af7c-4a23-b4d0-a84b2ce58e55.png)
![image](https://user-images.githubusercontent.com/34194191/189479804-ea2ed68f-4e3a-4c20-b5ed-69832ffa83b3.png)
![image](https://user-images.githubusercontent.com/34194191/189479812-46ec6463-212d-4da0-b2dd-6c4ee84e7683.png)

------------------------
The hint "The LED is always in default state off." is wrong. When the "Default state" option is checked, the LEDs are always on, not off.

![image](https://user-images.githubusercontent.com/34194191/189496148-234fbede-fa06-4b45-82ba-04cacdacd2cf.png)

**Comment by erayrafet** [comment] 2022-09-10 18:02
Seems like V6 of the router supports those higher frequency bands (has a slightly different chip), but support for it is still WIP. This variant does not.

**Comment by Shine-** [comment] 2022-09-11 18:51
Tested channel 100 on a C50v4 and it's working perfectly fine. 5GHz Hardware (MT7612E) supports these channels. You have probably just forgotten to set your country code, so only "world" channels (36-48) are allowed in your configuration.

**Comment by erayrafet** [comment] 2022-09-11 18:56
> Tested channel 100 on a C50v4 and it's working perfectly fine. 5GHz Hardware (MT7612E) supports these channels. You have probably just forgotten to set your country code, so only "world" channels (36-48) are allowed in your configuration.
 
Well, the stock firmware doesn't allow anything higher, and OpenWRT wouldn't initialize my 5GHz with a higher channel set. Alright, I set the country code to world and nada.
![image](https://user-images.githubusercontent.com/34194191/189544433-dec1b114-6e22-41b2-9bfa-b4a05a978441.png)

**Comment by erayrafet** [comment] 2022-09-11 19:08
So, setting the country code to US fixes the "Not associated issue" while the 00 option borks it.

**Comment by erayrafet** [comment] 2022-09-11 19:12
Using channel 165 that can be selected results in the same "Not associated" message.

**Comment by Shine-** [comment] 2022-09-11 19:16
World -> 36-48 only
HW Default -> probably same as "World" for this device
Any other country code -> channels allowed as per regulatrory rules for that country.

Works as designed.

**Comment by erayrafet** [comment] 2022-09-11 19:18
Well, the US seems to allow channel 165, as well as China, the UK, Singapore which I've tested, but it's a no go. At least the issue text can be more descriptive.

**Comment by Shine-** [comment] 2022-09-11 19:20
Perhaps you have left bandwidth at "80MHz"? 165 is a 20MHz channel, so again, works as designed.

**Comment by erayrafet** [comment] 2022-09-11 19:21
Indeed, I've set the channel width to 80 which channel 165 apparently doesn't support. I've learned so many new things tonight.

**Comment by Shine-** [comment] 2022-09-11 19:33
I have to correct myself, 165 is also a 40 (165-169) and 80 MHz (165-177) channel, at least for US regulatory domain. Maybe not be supported by the hardware as such, though.

**Comment by erayrafet** [comment] 2022-09-11 20:03
@Shine- Thank you for the information. Now I do run channel 161 instead of 48. Ping seems very good.

**Comment by erayrafet** [comment] 2022-09-11 20:12
I can even increase the transmit power from the default 20mV to 22 with US set as country code.
Though, it seems like channel 14 for 2.4GHz isn't supported by the hardware.

**Comment by Shine-** [comment] 2022-09-11 21:35
14 -> Japan only.
possible TX power -> also depends on antenna gain

You might be better off asking your questions in the forum instead and close this issue, since none of this seems to be an actual issue with OpenWRT, but rather beginner's usage questions.

**Comment by erayrafet** [comment] 2022-09-12 03:40
Well, the UI could use some changes like hiding channels not supported because of the country code set. Also, getting more descriptive error messages and not like Microsoft with errors like "Something happened." Not a great user experience, even though this is software for experienced users.

**Comment by erayrafet** [comment] 2022-09-12 04:04
At 2.4GHz, channels 13-14 were hidden until I set the country code to Japan. There's definitely an issue here since I can see channels through 165 on 5GHz with country code set to world, driver default, etc. The unsupported channels are always displayed there, but not for 2.4GHz.

**Comment by Shine-** [comment] 2022-09-12 07:17
LuCI lets you select whatever the driver exposes. Also see `iw phy phy1 info` (phy1 is 5G for your device). LuCI doesn't do any sanitizing against the RegDB on its own, why should it. And the MT76 the driver **does** filter available frequencies against the country code that you have set before (unavailable frequencies showing as "disabled" in the `iw` output).

If the driver exposes unsupported frequencies for certain generic country codes (ie. "driver default" or "world"), that's usually improper EEPROM presets, ie. the device vendor's fault, not LuCI's fault.

As I said, better head over to the forum, as what you're experiencing are beginners pains, not actual issues with OpenWRT.

**Closed** 2022-09-12 08:35 UTC
