### ISSUE TITLE
Nanopi R1 gives no ip with squash and ext4 22.03.2 images

### ISSUE THREAD

**Issue by linxcow** [openwrt/openwrt#11469] opened 2022-12-11 08:12 UTC
Device : Nanopi R1 512MB ram H3 no emmc 
the system boots and gives ip with an older version of friendlywrt and works thereafter.

with the same SD card and both images as below i never get ip on  wired device on LAN

- openwrt-22.03.2-53b24516c538-sunxi-cortexa7-friendlyarm_nanopi-r1-squashfs-sdcard.img.gz
- openwrt-22.03.2-sunxi-cortexa7-friendlyarm_nanopi-r1-ext4-sdcard.img.gz

Below is a debug dump using the serial uart running the ext4 version:

```
[  574.755587] usb 1
U-Boot SPL 2020.04-OpenWrt-r19803-9a599fee93 (Oct 14 2022 - 22:44:41 +0000)
DRAM: 512 MiB
Trying to boot from MMC1


U-Boot 2020.04-OpenWrt-r19803-9a599fee93 (Oct 14 2022 - 22:44:41 +0000) Allwinner Technology

CPU:   Allwinner H3 (SUN8I 1680)
Model: FriendlyARM NanoPi R1
DRAM:  512 MiB
MMC:   Device 'mmc@1c11000': seq 1 is in use by 'mmc@1c10000'
mmc@1c0f000: 0, mmc@1c10000: 2, mmc@1c11000: 1
Loading Environment from FAT... Card did not respond to voltage select!
In:    serial
Out:   serial
Err:   serial
Net:   phy interface7

Error: ethernet@1c30000 address not set.
No ethernet found.

starting USB...
Bus usb@1c1b000: USB EHCI 1.00
Bus usb@1c1b400: USB OHCI 1.0
Bus usb@1c1c000: USB EHCI 1.00
Bus usb@1c1c400: USB OHCI 1.0
Bus usb@1c1d000: USB EHCI 1.00
Bus usb@1c1d400: USB OHCI 1.0
scanning bus usb@1c1b000 for devices... 2 USB Device(s) found
scanning bus usb@1c1b400 for devices... 1 USB Device(s) found
scanning bus usb@1c1c000 for devices... 1 USB Device(s) found
scanning bus usb@1c1c400 for devices... 1 USB Device(s) found
scanning bus usb@1c1d000 for devices... 1 USB Device(s) found
scanning bus usb@1c1d400 for devices... 1 USB Device(s) found
       scanning usb for storage devices... 0 Storage Device(s) found
Hit any key to stop autoboot:  0 
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
Found U-Boot script /boot.scr
377 bytes read in 2 ms (183.6 KiB/s)
## Executing script at 43100000
3359912 bytes read in 252 ms (12.7 MiB/s)
23066 bytes read in 5 ms (4.4 MiB/s)
## Booting kernel from Legacy Image at 42000000 ...
   Image Name:   ARM OpenWrt Linux-5.10.146
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    3359848 Bytes = 3.2 MiB
   Load Address: 40008000
   Entry Point:  40008000
   Verifying Checksum ... OK
## Flattened Device Tree blob at 43000000
   Booting using the fdt blob at 0x43000000
   Loading Kernel Image
   Using Device Tree in place at 43000000, end 43008a19

Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 5.10.146 (builder@buildhost) (arm-openwrt-linux-muslgnueabi-gcc (OpenWrt GCC 11.2.0 r19803-9a5992
[    0.000000] CPU: ARMv7 Processor [410fc075] revision 5 (ARMv7), cr=30c5387d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt: Machine model: FriendlyARM NanoPi R1
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000040000000-0x000000005fffffff]
[    0.000000]   HighMem  empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000040000000-0x000000005fffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000040000000-0x000000005fffffff]
[    0.000000] psci: probing for conduit method from DT.
[    0.000000] psci: Using PSCI v0.1 Function IDs from DT
[    0.000000] percpu: Embedded 15 pages/cpu s30732 r8192 d22516 u61440
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 129920
[    0.000000] Kernel command line: console=ttyS0,115200 earlyprintk root=/dev/mmcblk0p2 rootwait
[    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 505528K/524288K available (7555K kernel code, 838K rwdata, 1228K rodata, 2048K init, 257K bss, 18760K )
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] rcu:     RCU restricting CPUs from NR_CPUS=8 to nr_cpu_ids=4.
[    0.000000]  Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=4
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] GIC: Using split EOI/Deactivate mode
[    0.000000] clocksource: timer: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 79635851949 ns
[    0.000000] arch_timer: cp15 timer(s) running at 24.00MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x588fe9dc0, max_idle_ns: 440795202592 ns
[    0.000013] sched_clock: 56 bits at 24MHz, resolution 41ns, wraps every 4398046511097ns
[    0.000037] Switching to timer-based delay loop, resolution 41ns
[    0.000422] Console: colour dummy device 80x30
[    0.000514] Calibrating delay loop (skipped), value calculated using timer frequency.. 48.00 BogoMIPS (lpj=240000)
[    0.000550] pid_max: default: 32768 minimum: 301
[    0.000842] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.000869] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.002408] CPU: Testing write buffer coherency: ok
[    0.003068] /cpus/cpu@0 missing clock-frequency property
[    0.003118] /cpus/cpu@1 missing clock-frequency property
[    0.003154] /cpus/cpu@2 missing clock-frequency property
[    0.003191] /cpus/cpu@3 missing clock-frequency property
[    0.003215] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.004540] Setting up static identity map for 0x40200000 - 0x40200060
[    0.004794] rcu: Hierarchical SRCU implementation.
[    0.005184] dyndbg: Ignore empty _ddebug table in a CONFIG_DYNAMIC_DEBUG_CORE build
[    0.005920] smp: Bringing up secondary CPUs ...
[    0.017295] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
[    0.028862] CPU2: thread -1, cpu 2, socket 0, mpidr 80000002
[    0.040287] CPU3: thread -1, cpu 3, socket 0, mpidr 80000003
[    0.040455] smp: Brought up 1 node, 4 CPUs
[    0.040504] SMP: Total of 4 processors activated (192.00 BogoMIPS).
[    0.040519] CPU: All CPU(s) started in HYP mode.
[    0.040531] CPU: Virtualization extensions available.
[    0.050766] VFP support v0.3: implementor 41 architecture 2 part 30 variant 7 rev 5
[    0.051219] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.051263] futex hash table entries: 1024 (order: 4, 65536 bytes, linear)
[    0.051712] pinctrl core: initialized pinctrl subsystem
[    0.054798] NET: Registered protocol family 16
[    0.055581] DMA: preallocated 256 KiB pool for atomic coherent allocations
[    0.058082] thermal_sys: Registered thermal governor 'step_wise'
[    0.058865] No ATAGs?
[    0.117985] SCSI subsystem initialized
[    0.119032] usbcore: registered new interface driver usbfs
[    0.119185] usbcore: registered new interface driver hub
[    0.119322] usbcore: registered new device driver usb
[    0.119974] pps_core: LinuxPPS API ver. 1 registered
[    0.120001] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.120057] PTP clock support registered
[    0.120632] Advanced Linux Sound Architecture Driver Initialized.
[    0.123554] clocksource: Switched to clocksource arch_sys_counter
[    0.135135] NET: Registered protocol family 2
[    0.135658] IP idents hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    0.138152] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 6144 bytes, linear)
[    0.138254] TCP established hash table entries: 4096 (order: 2, 16384 bytes, linear)
[    0.138345] TCP bind hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    0.138475] TCP: Hash tables configured (established 4096 bind 4096)
[    0.138677] UDP hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.138746] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.139139] NET: Registered protocol family 1
[    0.141966] workingset: timestamp_bits=14 max_order=17 bucket_order=3
[    0.150146] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.150379] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.152587] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 248)
[    0.164491] sun8i-h3-pinctrl 1c20800.pinctrl: initialized sunXi PIO driver
[    0.167947] sun8i-h3-r-pinctrl 1f02c00.pinctrl: initialized sunXi PIO driver
[    0.182516] Serial: 8250/16550 driver, 16 ports, IRQ sharing enabled
[    0.188151] sun8i-h3-pinctrl 1c20800.pinctrl: supply vcc-pa not found, using dummy regulator
[    0.189206] printk: console [ttyS0] disabled
[    0.209537] 1c28000.serial: ttyS0 at MMIO 0x1c28000 (irq = 47, base_baud = 1500000) is a U6_16550A
[    0.808499] printk: console [ttyS0] enabled
[    0.824071] loop: module loaded
[    0.827770] Loading iSCSI transport class v2.0-870.
[    0.840084] sun8i-h3-pinctrl 1c20800.pinctrl: supply vcc-pd not found, using dummy regulator
[    0.849014] dwmac-sun8i 1c30000.ethernet: IRQ eth_wake_irq not found
[    0.855428] dwmac-sun8i 1c30000.ethernet: IRQ eth_lpi not found
[    0.863211] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    0.869813] ehci-platform: EHCI generic platform driver
[    0.875655] ehci-platform 1c1b000.usb: EHCI Host Controller
[    0.881285] ehci-platform 1c1b000.usb: new USB bus registered, assigned bus number 1
[    0.889340] ehci-platform 1c1b000.usb: irq 36, io mem 0x01c1b000
[    0.923540] ehci-platform 1c1b000.usb: USB 2.0 started, EHCI 1.00
[    0.930074] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 5.10
[    0.938390] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.945639] usb usb1: Product: EHCI Host Controller
[    0.950523] usb usb1: Manufacturer: Linux 5.10.146 ehci_hcd
[    0.956131] usb usb1: SerialNumber: 1c1b000.usb
[    0.961530] hub 1-0:1.0: USB hub found
[    0.965438] hub 1-0:1.0: 1 port detected
[    0.970906] ehci-platform 1c1c000.usb: EHCI Host Controller
[    0.976598] ehci-platform 1c1c000.usb: new USB bus registered, assigned bus number 2
[    0.984613] ehci-platform 1c1c000.usb: irq 38, io mem 0x01c1c000
[    1.013537] ehci-platform 1c1c000.usb: USB 2.0 started, EHCI 1.00
[    1.019978] usb usb2: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 5.10
[    1.028284] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.035528] usb usb2: Product: EHCI Host Controller
[    1.040412] usb usb2: Manufacturer: Linux 5.10.146 ehci_hcd
[    1.046004] usb usb2: SerialNumber: 1c1c000.usb
[    1.051319] hub 2-0:1.0: USB hub found
[    1.055204] hub 2-0:1.0: 1 port detected
[    1.060579] ehci-platform 1c1d000.usb: EHCI Host Controller
[    1.066258] ehci-platform 1c1d000.usb: new USB bus registered, assigned bus number 3
[    1.074292] ehci-platform 1c1d000.usb: irq 40, io mem 0x01c1d000
[    1.103540] ehci-platform 1c1d000.usb: USB 2.0 started, EHCI 1.00
[    1.109982] usb usb3: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 5.10
[    1.118311] usb usb3: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.125575] usb usb3: Product: EHCI Host Controller
[    1.130459] usb usb3: Manufacturer: Linux 5.10.146 ehci_hcd
[    1.136058] usb usb3: SerialNumber: 1c1d000.usb
[    1.141463] hub 3-0:1.0: USB hub found
[    1.145365] hub 3-0:1.0: 1 port detected
[    1.150495] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    1.156779] ohci-platform: OHCI generic platform driver
[    1.162612] ohci-platform 1c1b400.usb: Generic Platform OHCI controller
[    1.169310] ohci-platform 1c1b400.usb: new USB bus registered, assigned bus number 4
[    1.177334] ohci-platform 1c1b400.usb: irq 37, io mem 0x01c1b400
[    1.247872] usb usb4: New USB device found, idVendor=1d6b, idProduct=0001, bcdDevice= 5.10
[    1.253539] usb 1-1: new high-speed USB device number 2 using ehci-platform
[    1.256183] usb usb4: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.270391] usb usb4: Product: Generic Platform OHCI controller
[    1.276345] usb usb4: Manufacturer: Linux 5.10.146 ohci_hcd
[    1.281938] usb usb4: SerialNumber: 1c1b400.usb
[    1.287331] hub 4-0:1.0: USB hub found
[    1.291175] hub 4-0:1.0: 1 port detected
[    1.296596] ohci-platform 1c1c400.usb: Generic Platform OHCI controller
[    1.303292] ohci-platform 1c1c400.usb: new USB bus registered, assigned bus number 5
[    1.311336] ohci-platform 1c1c400.usb: irq 39, io mem 0x01c1c400
[    1.387861] usb usb5: New USB device found, idVendor=1d6b, idProduct=0001, bcdDevice= 5.10
[    1.396167] usb usb5: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.403395] usb usb5: Product: Generic Platform OHCI controller
[    1.409339] usb usb5: Manufacturer: Linux 5.10.146 ohci_hcd
[    1.414978] usb usb5: SerialNumber: 1c1c400.usb
[    1.420338] hub 5-0:1.0: USB hub found
[    1.424232] hub 5-0:1.0: 1 port detected
[    1.429573] ohci-platform 1c1d400.usb: Generic Platform OHCI controller
[    1.436310] ohci-platform 1c1d400.usb: new USB bus registered, assigned bus number 6
[    1.444355] ohci-platform 1c1d400.usb: irq 41, io mem 0x01c1d400
[    1.465203] usb 1-1: New USB device found, idVendor=0bda, idProduct=8152, bcdDevice=20.00
[    1.473390] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    1.480575] usb 1-1: Product: USB 10/100 LAN
[    1.484874] usb 1-1: Manufacturer: Realtek
[    1.488978] usb 1-1: SerialNumber: 000000000000
[    1.527876] usb usb6: New USB device found, idVendor=1d6b, idProduct=0001, bcdDevice= 5.10
[    1.536204] usb usb6: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.543432] usb usb6: Product: Generic Platform OHCI controller
[    1.549422] usb usb6: Manufacturer: Linux 5.10.146 ohci_hcd
[    1.555023] usb usb6: SerialNumber: 1c1d400.usb
[    1.560315] hub 6-0:1.0: USB hub found
[    1.564194] hub 6-0:1.0: 1 port detected
[    1.569629] usbcore: registered new interface driver usb-storage
[    1.576719] mousedev: PS/2 mouse device common for all mice
[    1.585000] sun6i-rtc 1f00000.rtc: registered as rtc0
[    1.590182] sun6i-rtc 1f00000.rtc: setting system clock to 1970-01-01T00:00:13 UTC (13)
[    1.598220] sun6i-rtc 1f00000.rtc: RTC enabled
[    1.603006] i2c /dev entries driver
[    1.609302] sunxi-wdt 1c20ca0.watchdog: Watchdog enabled (timeout=16 sec, nowayout=0)
[    1.618201] sun8i-h3-r-pinctrl 1f02c00.pinctrl: supply vcc-pl not found, using dummy regulator
[    1.628653] sun8i-h3-pinctrl 1c20800.pinctrl: supply vcc-pf not found, using dummy regulator
[    1.628732] sun8i-h3-pinctrl 1c20800.pinctrl: supply vcc-pg not found, using dummy regulator
[    1.629136] sun8i-h3-pinctrl 1c20800.pinctrl: supply vcc-pg not found, using dummy regulator
[    1.632156] sun8i-h3-pinctrl 1c20800.pinctrl: supply vcc-pc not found, using dummy regulator
[    1.637261] NET: Registered protocol family 10
[    1.638684] sunxi-mmc 1c0f000.mmc: Got CD GPIO
[    1.648490] sunxi-mmc 1c10000.mmc: allocated mmc-pwrseq
[    1.663593] sunxi-mmc 1c11000.mmc: initialized, max. request size: 16384 KB
[    1.663645] sunxi-mmc 1c0f000.mmc: initialized, max. request size: 16384 KB
[    1.692400] Segment Routing with IPv6
[    1.692788] sunxi-mmc 1c10000.mmc: initialized, max. request size: 16384 KB
[    1.696294] NET: Registered protocol family 17
[    1.707895] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfi.
[    1.721318] can: controller area network core
[    1.725900] NET: Registered protocol family 29
[    1.730377] 8021q: 802.1Q VLAN Support v1.8
[    1.734818] Registering SWP/SWPB emulation handler
[    1.748731] mmc2: queuing unknown CIS tuple 0x80 (2 bytes)
[    1.755894] mmc2: queuing unknown CIS tuple 0x80 (3 bytes)
[    1.759358] sun8i-h3-pinctrl 1c20800.pinctrl: supply vcc-pd not found, using dummy regulator
[    1.769949] mmc1: host does not support reading read-only switch, assuming write-enable
[    1.778277] mmc1: new high speed SDHC card at address aaaa
[    1.779222] mmc2: queuing unknown CIS tuple 0x80 (3 bytes)
[    1.780559] dwmac-sun8i 1c30000.ethernet: IRQ eth_wake_irq not found
[    1.780573] dwmac-sun8i 1c30000.ethernet: IRQ eth_lpi not found
[    1.781180] dwmac-sun8i 1c30000.ethernet: PTP uses main clock
[    1.781231] dwmac-sun8i 1c30000.ethernet: Current syscon value is not the default 50006 (expect 58000)
[    1.791283] mmcblk1: mmc1:aaaa SU16G 14.8 GiB 
[    1.798532] mmc2: queuing unknown CIS tuple 0x80 (7 bytes)
[    1.803888]  mmcblk1: p1 p2
[    1.810906] mmc2: queuing unknown CIS tuple 0x81 (9 bytes)
[    1.903980] dwmac-sun8i 1c30000.ethernet: No HW DMA feature register supported
[    1.911236] dwmac-sun8i 1c30000.ethernet: RX Checksum Offload Engine supported
[    1.918536] dwmac-sun8i 1c30000.ethernet: COE Type 2
[    1.923550] dwmac-sun8i 1c30000.ethernet: TX Checksum insertion supported
[    1.930354] dwmac-sun8i 1c30000.ethernet: Normal descriptors
[    1.936050] dwmac-sun8i 1c30000.ethernet: Chain mode enabled
[    1.941775] dwmac-sun8i 1c30000.ethernet: device MAC address 5e:3b:e5:c7:40:12
[    1.952960] dwmac-sun8i 1c30000.ethernet: Found internal PHY node
[    1.960149] dwmac-sun8i 1c30000.ethernet: Switch mux to internal PHY
[    1.966582] dwmac-sun8i 1c30000.ethernet: Powering internal PHY
[    1.974768] dwmac-sun8i 1c30000.ethernet: Switch mux to external PHY
[    1.989826] mmc2: new high speed SDIO card at address 0001
[    2.000948] cpufreq: cpufreq_online: CPU0: Running at unlisted initial frequency: 480000 KHz, changing to: 648000 KHz
[    2.022530] ALSA device list:
[    2.025561]   No soundcards found.
[    2.029413] Waiting for root device /dev/mmcblk0p2...
[   32.483504] vcc3v0: disabling
[   32.486485] vcc5v0: disabling

```

**Comment by AiyionPrime** [comment] 2022-12-12 08:28
@linxcow already found it, but for others coming along:
This looks like the second problem of #11104.

**Comment by stintel** [comment] 2022-12-22 11:48
Dupe of #10080.

**Closed by stintel** 2022-12-22 11:48 UTC
