### ISSUE TITLE
Wireguard route issue in recent snapshots

### ISSUE THREAD

**Issue by whiskerp** [openwrt/openwrt#13985] opened 2023-11-15 12:25 UTC
### Describe the bug

Having tried the 20-Oct snapshot of 23.05 for Lantiq BT HomeHub 5A and found it worked well, I flashed the 11-Nov snapshot. 

However in this newer snapshot Wireguard routes are being inserted with the first octet set to zero.

The command "wg" shows the correct route (for example 192.168.1.0/24) however "ip route" shows 0.168.1.0/24 in the routing table.

### OpenWrt version

23.05 snapshot 11-Nov-2023

### OpenWrt release

23.05

### OpenWrt target/subtarget

23.05

### Device

BT Home Hub 5A

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by jow-** [comment] 2023-11-16 10:29
Likely duplicate of https://github.com/openwrt/netifd/issues/17 - make sure to update the netifd package to at least version 2023-11-10-35facc83-1.1 or the entire system to at least version 23.05.2 or a 23.05 snapshot later than Nov 15

**Closed** 2023-11-16 10:29 UTC
Labels: bug, invalid
