### ISSUE TITLE
Ubnt Nanostation AC loco fails to store config after upgrade to 23.05

### ISSUE THREAD

**Issue by pswilde** [openwrt/openwrt#13750] opened 2023-10-20 14:48 UTC
### Describe the bug

I have many Ubiquiti Nanostation 5 AC loco devices, that have been running 22.03 fine for ages. I thought I'd try upgrading to 23.05 but it appears after upgrade configuration cannot be stored. Anything configured is fine at runtime, and operates well while the device is on, but if anything interrupts the power or if the device is manually rebooted, all configuration is lost.

I have spare devices, and have reverted one back to 22.03.5 which is again working fine (although I had to use Ubiquiti's TFTP factory image process as downgrading from OpenWRT didn't work.... because a reset just applies the current 23.05 image again)

I think it may be something to do with the mounts, but I am by no means an expert here.

I have performed an upgrade on two different Nanostation AC locos, one brand new, and the result is the same.

Thanks,

### OpenWrt version

r23389-5deed175a5

### OpenWrt target/subtarget

ath79/generic

### Device

Ubiquiti Nanostation AC loco (WA)

### Image kind

Official downloaded image

### Steps to reproduce

1. Flash 23.05 (tried both rc3 and release 23.05) to device
2. Configure anything i.e. system name, password, wireless, dhcp, etc.
3. Reboot
4. Configuration is lost.

### Actual behaviour

Device does not keep any information after reboot or power loss

### Expected behaviour

Device should persist configuration

### Additional info

Output of df -h on **23.05**
```
Filesystem                Size      Used Available Use% Mounted on
/dev/root                 4.0M      4.0M         0 100% /rom
tmpfs                    27.9M     76.0K     27.8M   0% /tmp
/dev/mtdblock5            9.3M      9.3M         0 100% /overlay
tmpfs                    27.9M     84.0K     27.8M   0% /tmp/root
overlayfs:/tmp/root      27.9M     84.0K     27.8M   0% /
tmpfs                   512.0K         0    512.0K   0% /dev
```

Output of df -h on **22.03**
```
Filesystem                Size      Used Available Use% Mounted on
/dev/root                 4.0M      4.0M         0 100% /rom
tmpfs                    28.0M    232.0K     27.8M   1% /tmp
/dev/mtdblock5            9.3M    436.0K      8.8M   5% /overlay
overlayfs:/overlay        9.3M    436.0K      8.8M   5% /
tmpfs                   512.0K         0    512.0K   0% /dev
```

Output of cat /proc/mtd on **23.05""
```
dev:    size   erasesize  name
mtd0: 00040000 00010000 "u-boot"
mtd1: 00010000 00010000 "u-boot-env"
mtd2: 00f60000 00010000 "firmware"
mtd3: 00240000 00010000 "kernel"
mtd4: 00d20000 00010000 "rootfs"
mtd5: 00950000 00010000 "rootfs_data"
mtd6: 00040000 00010000 "cfg"
mtd7: 00010000 00010000 "art"
```

Output of cat /proc/mtd on **22.03""
```
dev:    size   erasesize  name
mtd0: 00040000 00010000 "u-boot"
mtd1: 00010000 00010000 "u-boot-env"
mtd2: 00f60000 00010000 "firmware"
mtd3: 00230000 00010000 "kernel"
mtd4: 00d30000 00010000 "rootfs"
mtd5: 00940000 00010000 "rootfs_data"
mtd6: 00040000 00010000 "cfg"
mtd7: 00010000 00010000 "art"
```
Output of cat /proc/mounts on **23.05**
```
/dev/root /rom squashfs ro,relatime,errors=continue 0 0
proc /proc proc rw,nosuid,nodev,noexec,noatime 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,noatime 0 0
cgroup2 /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0
tmpfs /tmp tmpfs rw,nosuid,nodev,noatime 0 0
/dev/mtdblock5 /overlay jffs2 rw,noatime 0 0
tmpfs /tmp/root tmpfs rw,noatime,mode=755 0 0
overlayfs:/tmp/root / overlay rw,noatime,lowerdir=/,upperdir=/tmp/root/upper,workdir=/tmp/root/work 0 0
tmpfs /dev tmpfs rw,nosuid,noexec,noatime,size=512k,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,noatime,mode=600,ptmxmode=000 0 0
debugfs /sys/kernel/debug debugfs rw,noatime 0 0
bpffs /sys/fs/bpf bpf rw,nosuid,nodev,noexec,noatime,mode=700 0 0
```

Output of cat /proc/mounts on **22.03**
```
/dev/root /rom squashfs ro,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,noatime 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,noatime 0 0
cgroup2 /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0
tmpfs /tmp tmpfs rw,nosuid,nodev,noatime 0 0
/dev/mtdblock5 /overlay jffs2 rw,noatime 0 0
overlayfs:/overlay / overlay rw,noatime,lowerdir=/,upperdir=/overlay/upper,workdir=/overlay/work 0 0
tmpfs /dev tmpfs rw,nosuid,noexec,noatime,size=512k,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,noatime,mode=600,ptmxmode=000 0 0
debugfs /sys/kernel/debug debugfs rw,noatime 0 0
none /sys/fs/bpf bpf rw,nosuid,nodev,noexec,noatime,mode=700 0 0
```

If any more outputs will be useful, let me know I will keep a device on 23.05 for troubleshooting for now. I can also test any adjustments if you like.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment] 2023-10-20 16:07
You need to do reset aka firstboot. If you look carefully your overlayfs is full, probably you left some stray log or tcpdump out there.

**Comment by pswilde** [comment] 2023-10-20 16:28
Thanks, but unfortunately it isn't that. I didn't that initially myself but not the cause. I've done full resets, no joy.
I ended up thinking it may be the nanostation (which is about 6 years old) had dodgy storage so it went read-only, I bought two brand new nanostations but the exact same thing happens.
I think the 100% full storage is part of the bug unfortunately.

**Comment by brada4** [comment] 2023-10-20 17:02
Boot in safe mode - tap reset when led blinks fastest - and run firstboot ; reboot there

**Comment by pswilde** [comment] 2023-10-20 17:44
OK, I'll try that when I get a moment over the weekend.
Can I ask though, why would this be different in 23.05 than 22.03? Not saying you're wrong, but surely this is a bug if it has to be done on a device fresh out of the box?
For example, if I put 23.05 on the device I have this trouble, revert back to 22.03 (via Ubiquiti tftp recovery method) it's fine, but if I put 23.05 back on (either directly or via Ubiquiti tftp recovery method) I have the same issue again... go back to 22.03, fine again... and so on.

**Comment by brada4** [comment] 2023-10-20 18:24
Usually it happens when one leaves configuration over incompatible upgrade, like flash format changes, switch to ath79 architecture, switch starting to support DSA. Should not happen on a normal clean install from factory though. There is one in a million chance leftover bits after factory install in rootfs_data resemble jffs2 and the initial wipe is skipped. It should come up with like 100kb generated/extracted from SoC partitions conf files in overlay/rootfs_data and 192.168.1.1
Full jffs2 that you observe is anomaly , for obvious reasons you cannot save in it. jffs2 needs 2 free erase blocks to be writable.

**Comment by pswilde** [comment] 2023-10-20 18:39
Thanks for the info, I'll give it a go over the weekend and report back.
Thanks

**Comment by pswilde** [comment] 2023-10-21 16:00
Just an update - no joy with any of this I'm afraid. `firstboot; reboot` clears the overlay partition and reboots fine, but config still doesn't save after any subsequent reboots after that. I've tried a jffs2reset as well, still no joy after that.

Interesting development though, previously I was using 23.05-rc3 (one device was on 23.05-release which the same problems), but through many full resets, including factory resets to stock firmware of various versions, over the last few hours I'm on 23.05.0 release again now. The output for df is different, in that now the /overlay mount is not at 100% but still the config is not saving

Once again, if I factory restore to stock then put 22.03 on, things are perfect, back to 23.05, config doesn't save, back to 22.03, things are fine again.

I have 3 devices I can test with, 2 new from box, all have the same problem with 23.05. I can put 22.03 on them and they work perfectly.

Outputs below from 23.05

```
root@OpenWrt:~# df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root                 4.0M      4.0M         0 100% /rom
tmpfs                    27.9M     60.0K     27.9M   0% /tmp
tmpfs                    27.9M     64.0K     27.8M   0% /tmp/root
tmpfs                   512.0K         0    512.0K   0% /dev
/dev/mtdblock5            9.3M      2.9M      6.4M  31% /overlay
overlayfs:/overlay        9.3M      2.9M      6.4M  31% /
root@OpenWrt:~# cat /proc/mounts
/dev/root /rom squashfs ro,relatime,errors=continue 0 0
proc /proc proc rw,nosuid,nodev,noexec,noatime 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,noatime 0 0
cgroup2 /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0
tmpfs /tmp tmpfs rw,nosuid,nodev,noatime 0 0
tmpfs /tmp/root tmpfs rw,noatime,mode=755 0 0
tmpfs /dev tmpfs rw,nosuid,noexec,noatime,size=512k,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,noatime,mode=600,ptmxmode=000 0 0
debugfs /sys/kernel/debug debugfs rw,noatime 0 0
bpffs /sys/fs/bpf bpf rw,nosuid,nodev,noexec,noatime,mode=700 0 0
/dev/mtdblock5 /overlay jffs2 rw,noatime 0 0
overlayfs:/overlay / overlay rw,noatime,lowerdir=/,upperdir=/overlay/upper,workdir=/overlay/work 0 0
root@OpenWrt:~# cat /proc/mtd
dev:    size   erasesize  name
mtd0: 00040000 00010000 "u-boot"
mtd1: 00010000 00010000 "u-boot-env"
mtd2: 00f60000 00010000 "firmware"
mtd3: 00240000 00010000 "kernel"
mtd4: 00d20000 00010000 "rootfs"
mtd5: 00940000 00010000 "rootfs_data"
mtd6: 00040000 00010000 "cfg"
mtd7: 00010000 00010000 "art"
```

**Comment by brada4** [comment] 2023-10-21 16:25
Try this - if rootfs data is writable
```
touch /.mark
ls -l /.mark
sync
(dmesg/logread)
reboot
ls -l /.mark
```
In principle rw should turn ro on write failure in `mount` and write some messages to dmesg.

**Comment by voxelcat** [comment] 2023-10-22 03:43
There are multiple Ubnt devices having this issue for a while, including in 23.05 and current master. There is a forum topic about this: https://forum.openwrt.org/t/powerbeam-m5-xw-configuration-loss-after-reboot/141925

Do you also have these in your kernel log (`dmesg`)?

```
[   59.657641] jffs2_scan_eraseblock(): End of filesystem marker found at 0x0
[   59.664661] jffs2_build_filesystem(): unlocking the mtd device...
[   59.684993] done.
[   59.693240] jffs2_build_filesystem(): erasing all blocks after the end marker...
[   59.713506] jffs2: Newly-erased block contained word 0x19852003 at offset 0x00180000
[   59.759103] jffs2: Newly-erased block contained word 0x19852003 at offset 0x00170000
[   59.805047] jffs2: Newly-erased block contained word 0x19852003 at offset 0x00160000
[   59.835012] jffs2: Newly-erased block contained word 0x19852003 at offset 0x00150000
[   59.863037] jffs2: Newly-erased block contained word 0x19852003 at offset 0x00140000
[   59.905017] jffs2: Newly-erased block contained word 0x19852003 at offset 0x00130000
[   59.935015] jffs2: Newly-erased block contained word 0x19852003 at offset 0x00120000
[   59.974642] jffs2: Newly-erased block contained word 0x19852003 at offset 0x00110000
[   59.995010] jffs2: Newly-erased block contained word 0x19852003 at offset 0x00100000
[   60.017482] jffs2: Newly-erased block contained word 0x19852003 at offset 0x000f0000
[   60.037818] jffs2: Newly-erased block contained word 0x19852003 at offset 0x000e0000
[   60.057816] jffs2: Newly-erased block contained word 0x19852003 at offset 0x000d0000
[   60.077801] jffs2: Newly-erased block contained word 0x19852003 at offset 0x000c0000
[   60.097809] jffs2: Newly-erased block contained word 0x19852003 at offset 0x000b0000
[   60.117871] jffs2: Newly-erased block contained word 0x19852003 at offset 0x000a0000
[   60.145005] jffs2: Newly-erased block contained word 0x19852003 at offset 0x00090000
[   60.165005] jffs2: Newly-erased block contained word 0x19852003 at offset 0x00080000
[   60.187449] jffs2: Newly-erased block contained word 0x19852003 at offset 0x00070000
[   60.207821] jffs2: Newly-erased block contained word 0x19852003 at offset 0x00060000
[   60.227861] jffs2: Newly-erased block contained word 0x19852003 at offset 0x00050000
[   60.247814] jffs2: Newly-erased block contained word 0x19852003 at offset 0x00040000
[   60.267814] jffs2: Newly-erased block contained word 0x19852003 at offset 0x00030000
[   60.287817] jffs2: Newly-erased block contained word 0x19852003 at offset 0x00020000
[   60.307816] jffs2: Newly-erased block contained word 0x19852003 at offset 0x00010000
[   60.335006] jffs2: Newly-erased block contained word 0xdeadc0de at offset 0x00000000
[   60.342907] done.
[   60.344879] jffs2: notice: (1974) jffs2_build_xattr_subsystem: complete building xattr subsystem, 0 of xdatum (0 unchecked, 0 orphan) and 0 of xref (0 dead, 0 orphan) found.
```

**Comment by brada4** [comment] 2023-10-22 04:58
Seems every other device sometimes gets hurt....
https://forum.openwrt.org/t/ubiquiti-nanostation-m5-flash-chip-woes-no-settings-saved-after-reboot/29794

Flash IF frequency is set here, set it to half, spec says 133MHz write 50MHz read, this should be like well underclocked already even for old age.
https://github.com/openwrt/openwrt/blob/bb8fd41f9a6775734882fe9707f7ad5e5edfbf9e/target/linux/ath79/dts/ar9342_ubnt_wa.dtsi#L38

**Comment by brada4** [comment] 2023-10-22 05:03
Also if you have case open check if top right chip matches original model:
https://openwrt.org/_detail/media/ubiquiti/nanostation_ac/pcb.jpg?id=toh%3Aubiquiti%3Ananostation_ac_loco
If slower flash is manufactured frequ drop is certainly required.

**Comment by jmranger** [comment] 2023-11-18 18:19
One more case, on a Nanostation AC Loco, initially reported in #13991. Works fine in 22.03.5, but unable to write to flash (even sysupgrade does nothing) in 23.05.2.
Here's the 23.05.2 bootlog: [dmesg.txt](https://github.com/openwrt/openwrt/files/13401151/dmesg.txt)

A few notes:
- My device seems to have a slightly different NOR than the one mentioned in the [main forum thread](https://forum.openwrt.org/t/powerbeam-m5-xw-configuration-loss-after-reboot/141925) - mx25l12805d here.
- **Any chance this could be added to the known issues in the relase notes?** We have multiple reports, and in the most cursed cases, reverting requires to flash back Ubiquiti's firmware through TFTP, a process that isn't fun as-is, but that is made even worse considering that those devices are often installed outside, sometimes in hard to reach locations.

**Comment by nivex** [comment] 2023-12-04 00:40
I'll add a vote for putting this in the release notes. This evening I ran headlong into this issue, and I have not been able to `sysupgrade` back to 22.05.3 to get my device stable again.

**Comment by jmranger** [comment] 2023-12-09 00:18
Hi @nivex,
Were you able to recover it?
The process can be quite convoluted, but the worst case scenario of going back to the OEM firmware over TFTP and then back to 22.03 seems reliable. If you describe your issues in the [forum](https://forum.openwrt.org/t/powerbeam-m5-xw-configuration-loss-after-reboot/141925/15), I'm quite sure a solution can be found.

**Comment by nivex** [comment] 2023-12-11 20:29
@jmranger I finally had some time today to do the factory firmware dance. I'm on 22.03.6 now.

**Comment by jmranger** [comment] 2023-12-23 16:40
Just found that this bug is possibly a duplicate of #12882.

**Closed** 2023-12-24 11:44 UTC
Labels: bug
