### ISSUE TITLE
<uhttpd on mbedtls> cannot load a certificate chain (intermediate CA)

### ISSUE THREAD

**Issue by farfade** [openwrt/openwrt#13728] opened 2023-10-18 15:01 UTC
### Describe the bug

@hauke

Environment: ramips/mt7621 23.05.0

Description:

I face a regression starting from version 23, compared to version 22, for loading into uhttpd a certificate *chain* (with an intermediate certificate authority)

In version 22, I was using a standard PEM formatted certificate chain. All was simple and went well.

In version 23, I face the error "uhttpd: Failed to load certificate/key files".

This is a first problem : losing the ability to use PEM (text) certs chains. 

The second problem is that I tried to use DER as the documentation there https://openwrt.org/docs/guide-user/luci/getting_rid_of_luci_https_certificate_warnings says 

```openssl x509 -in /etc/letsencrypt/live/example.com/fullchain.pem -outform DER -out /tmp/uhttpd```

But it does not work neither : it only includes the first certificate of fullchain.pem (but not the full chain) in the DER output.
It means that in spite of having the DER certificate loaded by uhttpd, the user faces an error because the servers does not send any more the intermediate certificate.

Trying some well-known workarounds : embedding the chain into a PKCS7 package; or concatenating the intermediate cert as DER to the leaf cert as DER does not work neither.

It may be a regression due to the switch to mbedtls (which advertises it supports PEM).

Thanks for reading,

farfade

### OpenWrt version

23

### OpenWrt target/subtarget

ramips/mt7621

### Device

 D-Team Newifi D2

### Image kind

Official downloaded image

### Steps to reproduce

Generate a certificate containing a leaf cert and an intermediate cert

Use it in uhttpd config file after having it outformed as PEM or DER :

```
 option cert '/etc/config/ssl/pub.pem'
 option key '/etc/config/ssl/private/key.pem'
```

```
 option cert '/etc/config/ssl/pub.der'
 option key '/etc/config/ssl/private/key.der'
```

### Actual behaviour

For PEM, uhttpd does not restart : Failed to load certificate/key files

For DER,  the server does not send the intermediate cert to the browser

### Expected behaviour

Have the ability to use a PEM formatted certificate containing a chain of intermediate certificates

### Additional info

The expected behaviour was the one working in version 22.

So I think it is a regression linked to the switch to mbedtls.
mbedtls advertise they support PEM, so I think the bug is related to the way uhttpd uses mbedtls

The documentation here is also unaccurate : https://openwrt.org/docs/guide-user/luci/getting_rid_of_luci_https_certificate_warnings as it was stating that PEM was not supported in 22 (whereas it was) and that DER could contain a fullchain (with intermediate certs) althought it can't

### Diffconfig

No change of config between versions 22 and 23

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by Shine-** [comment] 2023-10-18 19:37
You got me almost afraid to have the next blocking issue here that prevents me from updating to 23.05...

But:
Can't confirm / works for me.

DER - not tested, as the DER format doesn't support certificate chains.

With PEM, I couldn't find **any** way, to provoke uhttp into throwing the "uhttpd: Failed to load certificate/key files" error you're describing.

Even with wrong chain order, wrong file permissions or when using Windows line feeds for example, uhttpd starts fine for me and listens on port 443. The difference is, when doing something wrong, 23.05 will time out any https connection attempt, while 22.03 leads to a "ERR_SSL_KEY_USAGE_INCOMPATIBLE" error in Chrome. Uhttpd will even happily serve a **wrong** chain (ie. a random other intermediate), as long as it's decodable - it doesn't have to match.

From reading your description, you seem to be having an issue only when your PEM chain contains a (ie. _your_) intermediate certificate. Could you perhaps attach your intermediate here? To preserve the encoding, as an attachment, not copy&paste, please.

**Comment by brada4** [comment] 2023-10-18 19:43
https://github.com/openwrt/packages/issues/22441 please close duplicate post

**Comment by farfade** [comment] 2023-10-21 11:25
Thank you @Shine- 

Here is my PEM chain with cert / intermediate and root. [cert.txt](https://github.com/openwrt/openwrt/files/13060541/cert.txt)

What I don't understand is that I did not change of even opened it since years and it was working with 22.

**Comment by Shine-** [comment] 2023-10-22 14:29
First, you have Windows line feeds in your "crt.txt" file. In my tests, Windows line feeds never worked, in any OpenWrt version I tested. Better convert your "cert.txt" to UNIX line feeds.

Second, all your certificates are using SHA512 ECDSA signatures - which is very (very!) uncommon. Probably mbedTLS 2.28, as used in OpenWrt 23.05, simply doesn't support it. After all, it doesn't even support TLS 1.3... You might be better off using a more common signature algorithm, such as SHA256. (Note: This is only a guess - I don't have a CA that signs using SHA512 ECDSA, so I can't test this myself).

Third (only an advice, has nothing to do with your issue), you're using a 4096 bit RSA public key. That's very demanding for the server device (ie. the OpenWrt router). If you want increased security over the common RSA 2048 bits, you might want to use P-256 instead, which causes much less load on server side.

A workaround for you might be to build a custom image using WolfSSL or OpenSSL, instead of mbedTLS, until OpenWrt finally switches to a more recent version of mbedTLS.

**Comment by farfade** [comment] 2023-10-22 19:05
Wise advices !

The line feeds change nothing however, and I don't go so often to openwrt ui, so the overload is not significant.

My combination is the result of parameters chosen in a global automation script that were the most secured and working a couple of years before on all of the assets I have. I didn't take into consideration regressions :) 
I should go for fine tailoring of my script... but I think I will live with the warning until the next version !

Thanks a lot for your interest, I really appreciated it.

Best,

farfade

**Comment by Shine-** [comment] 2023-10-23 08:45
Update:
I had some time today to play around a bit.

So the issue is not the SHA512 signing. The issue is that your intermediate and root CA keys are P-521.
Apparently the mbedTLS version used in OpenWrt supports only P-256 or P-384 when it comes to EC keys.

You might want to close this issue and re-open one with a proper description, as this one is very misleading - PEM chains are supported just fine. It's your P-521 Root-/Sub-CA certificates that aren't supported.

**Closed** 2023-10-23 13:39 UTC
Labels: bug

**Comment by farfade** [comment] 2023-10-23 13:41
@Shine- : thanks. Curiously, I use chrome and it supports my cert chain.

**Comment by farfade** [comment] 2023-10-23 13:54
Looking at mbedtls repository, I see references to P-521 [here](https://github.com/Mbed-TLS/mbedtls/blob/2bf0870e25fceb93f4b00e0b9142e26e3280168f/include/mbedtls/ecp.h#L528) and [there](https://github.com/Mbed-TLS/mbedtls/blob/2bf0870e25fceb93f4b00e0b9142e26e3280168f/tests/scripts/generate_tls13_compat_tests.py#L147)

But it is not clear to me if newer versions than the one embedded in openwrt support it.

**Comment by Shine-** [comment] 2023-10-23 14:03
Usually, such support needs to be compiled in. If it's not explicitly compiled in, you can't use it.
I personally would compile my embedded SSL libraries without P-521 for size reasons, since browser support is nonexistent anyway (ignore close-to-nonexistent market share of Firefox).
Therefore I suggested opening a new issue describing the regression and let the OpenWrt team decide whether they want to enable P-521 in future versions or not.

**Comment by farfade** [comment] 2023-11-01 13:45
Hi @Shine- ,

would you mind answering [a question here](https://github.com/openwrt/openwrt/issues/13774), on the reformulated topic ?

I cannot ping you from there.
