### ISSUE TITLE
image builder fails for espressobin in 19.07.9

### ISSUE THREAD

**Issue by hmoffatt** [openwrt/openwrt#9486] opened 2022-03-16 21:52 UTC
I am running the image builder with the command

```
        $(MAKE) -C $(DIR) image \
                CONFIG_TARGET_ROOTFS_PARTSIZE=256 \
                PROFILE=globalscale_espressobin \
                PACKAGES=$(PACKAGES)
```

In 19.07.8 and all earlier versions this works fine.

In 19.07.9, this fails with the error:

```
Traceback (most recent call last):
  File "/home/hamish/src/espresso-openwrt/openwrt-imagebuilder-19.07.9-mvebu-cortexa53.Linux-x86_64/scripts/json_add_image_info.py", line 34, in <module>
    "source_date_epoch": int(getenv("SOURCE_DATE_EPOCH")),
ValueError: invalid literal for int() with base 10: ''
make[4]: *** [Makefile:117: /home/hamish/src/espresso-openwrt/openwrt-imagebuilder-19.07.9-mvebu-cortexa53.Linux-x86_64/build_dir/target-aarch64_cortex-a53_musl/json_info_files/openwrt-19.07.9-mvebu-cortexa53-globalscale_espressobin-squashfs-sdcard.img.gz.json] Error 1
make[3]: *** [Makefile:172: build_image] Error 2
make[2]: *** [Makefile:120: _call_image] Error 2
make[1]: *** [Makefile:208: image] Error 2
```

**Comment by ynezz** [comment] 2022-03-17 18:46
It's fixed, it's duplicate of #9386, workaround:

```
$ sed -i 's,^# SOURCE_DATE_EPOCH:=.*,SOURCE_DATE_EPOCH:=1645044479,g' include/version.mk
```

**Closed by ynezz** 2022-03-17 18:46 UTC
