### ISSUE TITLE
Octeon (e.g. Ubiquiti EdgeRouter) can't read /etc/TZ

### ISSUE THREAD

**Issue by glyndon** [openwrt/openwrt#10309] opened 2022-07-19 16:12 UTC
This is a new report for existing open Issue #1138874404 using corrected spelling for the processor and affected systems, in hopes it causes the bots to bring to the attention of the proper people.

[https://github.com/openwrt/openwrt/issues/8941#issue-1138874404](https://github.com/openwrt/openwrt/issues/8941#issue-1138874404) has not been auto-assigned for a year.

From the evidence noted in issue #1138874404 and and other notes in the Forum, it appears there is a defect in the library used by OpenWrt (i.e. not a bug in OpenWrt itself) in how /etc/localtime is parsed.

**Comment by jow-** [comment] 2022-07-19 17:14
Duplicate of #8941

**Closed by jow-** 2022-07-19 17:14 UTC
