### ISSUE TITLE
hi  @jow- The problem has not been solved，

### ISSUE THREAD

**Issue by yangqingshi** [openwrt/openwrt#9939] opened 2022-05-25 06:25 UTC
hi  @jow- The problem has not been solved，
**First of all**, the probability of this problem happening is not 100%. But once it happens,  will always happening even reboot。
**next**，I noticed that it's related to  with the user of the file "/var/run/ubus.sock".
[2022-05-24 08:24:45.852954] 'srw-rw-rw-    1 **0**        root             0 Jan  1 00:00 /var/run/ubus.sock\r\n'
when the problem happening, the file user is  0, not root

_Originally posted by @yangqingshi in https://github.com/openwrt/openwrt/issues/9543#issuecomment-1136775054_

**Comment by ynezz** [comment] 2022-05-31 09:31
Duplicate of #9545

**Closed by ynezz** 2022-05-31 09:31 UTC
