### ISSUE TITLE
dnsmasq[1]: failed to create listening socket for fe80::200:5eff:fe00:1fc%pppoe-wan: Address not available

### ISSUE THREAD

**Issue by xiechangan123** [openwrt/openwrt#11464] opened 2022-12-10 11:26 UTC
release info: OpenWrt 22.03-SNAPSHOT r19977-6cd1035d8d / LuCI openwrt-22.03 branch git-22.339.35241-4ca7a8d
kernei: 5.10.156

log:
Sat Dec 10 15:32:11 2022 daemon.warn dnsmasq[1]: failed to create listening socket for fe80::200:5eff:fe00:1fc%pppoe-wan: Address not available
Sat Dec 10 15:32:11 2022 daemon.warn dnsmasq[1]: failed to create listening socket for fe80::200:5eff:fe00:1fc%pppoe-wan: Address not available
Sat Dec 10 15:52:21 2022 daemon.warn dnsmasq[1]: failed to create listening socket for fe80::200:5eff:fe00:1fc%pppoe-wan: Address not available
Sat Dec 10 15:52:21 2022 daemon.warn dnsmasq[1]: failed to create listening socket for fe80::200:5eff:fe00:1fc%pppoe-wan: Address not available
Sat Dec 10 16:12:32 2022 daemon.warn dnsmasq[1]: failed to create listening socket for fe80::200:5eff:fe00:1fc%pppoe-wan: Address not available
Sat Dec 10 16:12:32 2022 daemon.warn dnsmasq[1]: failed to create listening socket for fe80::200:5eff:fe00:1fc%pppoe-wan: Address not available
Sat Dec 10 16:32:41 2022 daemon.warn dnsmasq[1]: failed to create listening socket for fe80::200:5eff:fe00:1fc%pppoe-wan: Address not available
Sat Dec 10 16:32:41 2022 daemon.warn dnsmasq[1]: failed to create listening socket for fe80::200:5eff:fe00:1fc%pppoe-wan: Address not available
Sat Dec 10 16:52:51 2022 daemon.warn dnsmasq[1]: failed to create listening socket for fe80::200:5eff:fe00:1fc%pppoe-wan: Address not available
Sat Dec 10 16:52:51 2022 daemon.warn dnsmasq[1]: failed to create listening socket for fe80::200:5eff:fe00:1fc%pppoe-wan: Address not available
Sat Dec 10 17:13:02 2022 daemon.warn dnsmasq[1]: failed to create listening socket for fe80::200:5eff:fe00:1fc%pppoe-wan: Address not available
Sat Dec 10 17:13:02 2022 daemon.warn dnsmasq[1]: failed to create listening socket for fe80::200:5eff:fe00:1fc%pppoe-wan: Address not available
Sat Dec 10 17:33:11 2022 daemon.warn dnsmasq[1]: failed to create listening socket for fe80::200:5eff:fe00:1fc%pppoe-wan: Address not available
Sat Dec 10 17:33:11 2022 daemon.warn dnsmasq[1]: failed to create listening socket for fe80::200:5eff:fe00:1fc%pppoe-wan: Address not available

dnsmasq retries twice every 20 mins，this  problem has not been fixed

same problem：https://github.com/openwrt/openwrt/issues/9346

**Comment by jow-** [comment] 2022-12-10 19:20
Duplicate of #9346

**Closed by jow-** 2022-12-10 19:20 UTC
