### ISSUE TITLE
Regression: AVM FRITZ!Box 7362SL LAN ports 3 and 4 not working correctly on OpenWrt 21.02

### ISSUE THREAD

**Issue by skleeschulte** [openwrt/openwrt#5064] opened 2022-02-10 14:27 UTC
_Link to this issue in the old bugtracker: [FS#3832 - [Regression] xrx200 switch affecting AVM Fritz!Box 7362SL](https://bugs.openwrt.org/index.php?do=details&task_id=3832)_

**Recap:**

- The AVM FRITZ!Box 7362SL router has four LAN ports:
  - ports 1 and 2 support gigabit speed
  - ports 3 and 4 support fast ethernet speed
- On OpenWrt 19.07 (e.g. 19.07.7 kernel 4.14.221) all LAN ports are working correctly
- On OpenWrt 21.02 (e.g. OpenWrt 21.02.0-rc1 kernel 5.4.111, 21.02.1 kernel 5.4.154), LAN ports 1 and 2 work while LAN ports 3 and 4 are not working correctly:
  - physical link (layer 1) is working
  - fast ethernet connection is working
  - as soon as at least one gigabit speed capable device is connected to port 3 or 4, both ports stop working
  - when connecting a gigabit speed capable device to port 3 or 4, LuCI (/cgi-bin/luci/admin/network/switch) shows "1000baseT full-duplex" for that port, while only 100baseT would be supported by the router

**Selected quotes from the old issue:**

_Matthias Walther - 27.05.2021_
>  Notably might be the line ”failed to get the PCIe PHY“ which does not appear in 19.07.7.
> 
> As I didn’t notice any changes regarding this particular device model, it might be a problem with the kernel driver for the switch module.

_Matthias Walther - 02.06.2021_
> I also looked into the git history. Maybe this commit has something to do with the regression:
https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=f8ea7c53fd227a9c21f0ca45a2c3345312ea54b5

Various log-/debug-output can be found in the archived issue in the old bugtracker.

**Comment by jow-** [comment] 2022-02-20 23:57
Duplicate of #8833

**Closed by jow-** 2022-02-20 23:57 UTC
Labels: release/21.02
