### ISSUE TITLE
Drastic drop in 2.4GHz throughput is observed in OpenWrt 23.05.4 due to a mac80211 backport.

### ISSUE THREAD

**Issue by vochong** [openwrt/openwrt#15999] opened 2024-07-24 20:19 UTC
### Describe the bug

Some drastic drop (about by half)  in 2.4GHz throughput is observed in OpenWrt 23.05.4 due to the recent mac80211 backports.

Reverting this change  https://github.com/torvalds/linux/commit/4e5bd2287021823c10862379312648dd55e17f49 would restore the throughput back to normal.

More information about this issue (seen by multiple people):   https://forum.openwrt.org/t/ipq806x-nss-build-netgear-r7800-tp-link-c2600-linksys-ea8500/82525/4561

### OpenWrt version

r24012-d8dd03c46f

### OpenWrt release

23.05.4

### OpenWrt target/subtarget

ipq806x/generic

### Device

NETGEAR Nighthawk X4S R7800

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by egc112** [comment] 2024-07-25 06:09
I can confirm these findings and after building and removing the offending line my 2.4 GHz speed is doubled again because now 2 streams are used again

Question: Does this also apply to Main builds with kernel 6.6?

**Comment by tmn505** [comment] 2024-07-25 18:58
Follow-up on the issue: https://lore.kernel.org/all/29f7aa2c233277ab4bb56bcff8e228036ee96a2e.camel@sipsolutions.net
Please test.

**Comment by vochong** [comment] 2024-07-26 00:26
@nbd168

**Comment by AgustinLorenzo** [comment] 2024-07-26 08:25
> I can confirm these findings and after building and removing the offending line my 2.4 GHz speed is doubled again because now 2 streams are used. I compiled my own build using 23.05 Snapshot, you can find the patch I used at [my repo](https://github.com/egc112/OpenWRT-egc-add-on/blob/main/999-revert-set-station-rx-nss-on-reconfig-egc.patch)
> 
> Question: Does this also apply to Main builds with kernel 6.6?

Hi @egc112 

In effect, kernel 6.6 is also affected, see my comment on @hauke PR.

Regards, Agustin

**Comment by brada4** [comment] 2024-07-27 18:05
Cc TUF ax4200 , rt ax53u, c7v5

**Comment by hauke** [comment] 2024-08-03 13:23
Fixed in #16007

**Closed by hauke** 2024-08-03 13:23 UTC
Labels: target/ipq806x, bug, release/23.05, Official Image, Supported Device

**Comment by f45tb00t** [comment] 2024-09-10 19:33
I definitely can confirm. Updated my Ubiquiti LR 6 to 23.05.4 and the downstream decreased massively. Massively means from 1000++mbit down ~6mbit.  A rollback to .3 did the trick and fixed the situation.

Could you tell us please when a fixed version will be ready to install?

**Comment by brada4** [comment] 2024-09-10 19:35
You can try 23.05-SNAPSHOT (just install, document, get back to 23.05.3)

**Comment by f45tb00t** [comment] 2024-09-10 19:38
> You can try 23.05-SNAPSHOT (just install, document, get back to 23.05.3)

To be honest for this week I am done with TShooting.... Had also issues with my FW and other network equipment. Maybe next week.
