### ISSUE TITLE
DHCPv6 firewall default rule is wrong

### ISSUE THREAD

**Issue by owendelong** [openwrt/openwrt#11707] opened 2023-01-05 23:43 UTC
### Describe the bug

The /etc/config/firewall rule for DHCPv6 replies is as follows:
```
# Allow DHCPv6 replies
# see https://dev.openwrt.org/ticket/10381
config rule
        option name             Allow-DHCPv6
        option src              wan
        option proto            udp
        option src_ip           fc00::/6
        option dest_ip          fc00::/6
        option dest_port        546
        option family           ipv6
        option target           ACCEPT
```

There are a number of problems with the use of fc00::/6, not the least of which are that there is no reason to expect an ISP to necessarily provide DHCPv6 replies via LLA.

Other problems include that it not only covers ULA (fd00::/8) and LLA (fe80::/10) as intended, but also covers several IETF reserved ranges (fc00::/8, fe00::/9, fec0::/10) as well as multicast (ff00::/8).

The src_ip and dest_ip fields should be removed from the rule.

### OpenWrt version

r18195-d1c7df9c4b

### OpenWrt target/subtarget

mediatek/mt7622

### Device

Universal to all devices

### Image kind

Official downloaded image

### Steps to reproduce

No reproduction is really required. A simple review of /etc/config/firewall and examination of the rule replicated above will display the problem in plain sight.

### Actual behaviour

Depends on the ISP's behavior and other factors.

### Expected behaviour

DHCPv6 should work in as many circumstances as possible.

### Additional info

The removal of the two lines mentioned above is, IMHO, the best possible resolution to the problem in the current internet as it exists today. Something better would require broad standardization of optional behavior across a large number of ISPs which seems improbable and impractical.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by ynezz** [comment] 2023-01-06 09:45
Duplicate of #5066, should be fixed with 72b196da68526.

**Closed by ynezz** 2023-01-06 09:45 UTC
Labels: core packages, not a bug
