### ISSUE TITLE
23.05.0 IPv4 PPPoE software flow offload not working

### ISSUE THREAD

**Issue by InsaneKnight** [openwrt/openwrt#13847] opened 2023-11-01 15:34 UTC
### Describe the bug

The issue described in #10224 remains in 23.05.0.

### OpenWrt version

r23497-6637af95aa

### OpenWrt target/subtarget

ath79/generic

### Device

TP-Link Archer C7 v2

### Image kind

Self-built image

### Steps to reproduce

See #10224

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment] 2023-11-01 17:34
Please check with tcpdump (wireshark) on the client if replying SYN+ACK packets have MSS adjusted down from LAN default in SYN. The linked issue looks very sporadic at best with 3x dispersed results claimed then slow other time fast.

**Comment by jow-** [comment] 2023-11-01 21:56
Duplicate of #10224

**Closed by jow-** 2023-11-01 21:56 UTC
Labels: bug
