### ISSUE TITLE
21.02.1 squashfs overlay retained rpi4

### ISSUE THREAD

**Issue by CakeConnoisseur** [openwrt/openwrt#5087] opened 2022-02-13 13:59 UTC
Issue manually migrated from https://bugs.openwrt.org/index.php?do=details&task_id=4131

>Opened by [wulfy23](https://bugs.openwrt.org/index.php?do=user&area=users&id=1978) - 09.11.2021
>
>Upgrading from 21.02.0 to 21.02.1 leads to whacky opkg state where previous packages are listed
>
>see:
>https://forum.openwrt.org/t/rpi-4-sysupgrade-21-02-1-squashfs-overlay-retained/110586?u=wulfy23 for further information

>[wulfy23](https://bugs.openwrt.org/index.php?do=user&area=users&id=1978) commented on 09.11.2021 05:45
>note:
>
>selection of keep settings or not makes no difference and user configs are retained even without keep settings...
>
>21.02.0-rc4 > 21.02.0 (no problem)
>
>21.02.0 > 21.02.1 (problem)
>21.02.1 > 21.02.1 (problem)
>
>21.02.1 > master@r18xxx+ (no problem)

>[mojifax](https://bugs.openwrt.org/index.php?do=user&area=users&id=3663) commented on 09.11.2021 08:59
>i've noticed this in 21.02.0 > 21.02.0 also
>
>1- factory install
>2- set password
>3- reboot
>4- sysupgrade not retaining settings
>5- reboot password i still set
>
>https://forum.openwrt.org/t/raspberry-pi-4-usb-boot/109646/7

**Comment by walterav1984** [comment] 2022-02-16 20:46
Maybe related, hard (re-)imaging a factory squash RaspberryPi1 sdcard image using 'dd' over an exisiting configured sdcard squash image also keeps the config of the former installation... Using the ext4 image doesn't have this issue and clears the config.

**Comment by CakeConnoisseur** [comment] 2022-02-20 12:47
Please note that I opened this issue last week when there was conflicting information about whether or not the issues from the old bug repository would be automatically migrated or not.
Since then they have been migrated making #9113 and this one duplicates.

**Comment by jow-** [comment] 2022-02-20 23:00
Duplicate of https://github.com/openwrt/openwrt/issues/9113

**Closed by jow-** 2022-02-20 23:00 UTC
Labels: release/21.02
