### ISSUE TITLE
beagleboardblack fails to boot 21.02.1 sdcard image

### ISSUE THREAD

**Issue by efx** [openwrt/openwrt#5054] opened 2022-02-09 19:42 UTC
I have observed the issue described in https://bugs.openwrt.org/index.php?do=details&task_id=4237.

## basic steps
1. download image https://downloads.openwrt.org/releases/21.02.1/targets/omap/generic/openwrt-21.02.1-omap-ti_am335x-bone-black-squashfs-sdcard.img.gz
2. write it to an sdcard (`sudo dd if=openwrt-21.02.1-omap-ti_am335x-bone-black-squashfs-sdcard.img bs=1M of=/dev/mmcblk0`)
3. plug sdcard in and reboot bbb device

## logs

<details><summary>serial log</summary>

```
U-Boot SPL 2019.04-00002-g07d5700e21 (Mar 06 2020 - 11:24:55 -0600)
Trying to boot from MMC2
Loading Environment from EXT4... 
** Unable to use mmc 0:1 for loading the env **


U-Boot 2019.04-00002-g07d5700e21 (Mar 06 2020 - 11:24:55 -0600), Build: jenkins-github_Bootloader-Builder-137

CPU  : AM335X-GP rev 2.1
I2C:   ready
DRAM:  512 MiB
No match for driver 'omap_hsmmc'
No match for driver 'omap_hsmmc'
Some drivers were not found
Reset Source: Global warm SW reset has occurred.
Reset Source: Power-on reset has occurred.
RTC 32KCLK Source: External.
MMC:   OMAP SD/MMC: 0, OMAP SD/MMC: 1
Loading Environment from EXT4... 
** Unable to use mmc 0:1 for loading the env **
Board: BeagleBone Black
<ethaddr> not set. Validating first E-fuse MAC
BeagleBone Black:
BeagleBone: cape eeprom: i2c_probe: 0x54:
BeagleBone: cape eeprom: i2c_probe: 0x55:
BeagleBone: cape eeprom: i2c_probe: 0x56:
BeagleBone: cape eeprom: i2c_probe: 0x57:
Net:   eth0: MII MODE
cpsw, usb_ether
Press SPACE to abort autoboot in 0 seconds
board_name=[A335BNLT] ...
board_rev=[000C] ...
switch to partitions #0, OK
mmc0 is current device
SD/MMC found on device 0
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
Found U-Boot script /boot.scr
326 bytes read in 5 ms (63.5 KiB/s)
## Executing script at 80000000
3800360 bytes read in 336 ms (10.8 MiB/s)
58519 bytes read in 17 ms (3.3 MiB/s)
## Flattened Device Tree blob at 88000000
   Booting using the fdt blob at 0x88000000
   Loading Device Tree to 8ffee000, end 8ffff496 ... OK

Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 5.4.154 (builder@buildhost) (gcc version 8.4.0 (OpenWrt GCC 8.4.0 r16325-88151b8303)) #0 SMP Sun Oct 24 09:01:35 2021
[    0.000000] CPU: ARMv7 Processor [413fc082] revision 2 (ARMv7), cr=10c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt: Machine model: TI AM335x BeagleBone Black
[    0.000000] Memory policy: Data cache writeback
[    0.000000] cma: Reserved 16 MiB at 0x9ec00000
[    0.000000] CPU: All CPU(s) started in SVC mode.
[    0.000000] AM335X ES2.1 (sgx neon)
[    0.000000] percpu: Embedded 15 pages/cpu s31116 r8192 d22132 u61440
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 129412
[    0.000000] Kernel command line: console=ttyO0,115200n8 root=/dev/mmcblk0p2 rootwait
[    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 488620K/522240K available (8290K kernel code, 333K rwdata, 1528K rodata, 1024K init, 302K bss, 17236K reserved, 16384K cma-reserved, 0K highmem)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] rcu:     RCU restricting CPUs from NR_CPUS=4 to nr_cpu_ids=1.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=1
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] IRQ: Found an INTC at 0x(ptrval) (revision 5.0) with 128 interrupts
[    0.000000] random: get_random_bytes called from 0xc0b00bbc with crng_init=0
[    0.000000] OMAP clockevent source: timer2 at 24000000 Hz
[    0.000015] sched_clock: 32 bits at 24MHz, resolution 41ns, wraps every 89478484971ns
[    0.000037] clocksource: timer1: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 79635851949 ns
[    0.000047] OMAP clocksource: timer1 at 24000000 Hz
[    0.000546] timer_probe: no matching timers found
[    0.000679] Console: colour dummy device 80x30
[    0.000743] Calibrating delay loop... 996.14 BogoMIPS (lpj=4980736)
[    0.089202] pid_max: default: 32768 minimum: 301
[    0.089394] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.089407] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.090346] CPU: Testing write buffer coherency: ok
[    0.090422] CPU0: Spectre v2: using BPIALL workaround
[    0.090826] CPU0: thread -1, cpu 0, socket -1, mpidr 0
[    0.091507] Setting up static identity map for 0x80100000 - 0x80100060
[    0.091676] rcu: Hierarchical SRCU implementation.
[    0.091996] smp: Bringing up secondary CPUs ...
[    0.092008] smp: Brought up 1 node, 1 CPU
[    0.092017] SMP: Total of 1 processors activated (996.14 BogoMIPS).
[    0.092024] CPU: All CPU(s) started in SVC mode.
[    0.103091] VFP support v0.3: implementor 41 architecture 3 part 30 variant c rev 3
[    0.103322] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.103347] futex hash table entries: 256 (order: 2, 16384 bytes, linear)
[    0.104465] pinctrl core: initialized pinctrl subsystem
[    0.105883] NET: Registered protocol family 16
[    0.107838] DMA: preallocated 256 KiB pool for atomic coherent allocations
[    0.133334] l3-aon-clkctrl:0000:0: failed to disable
[    0.135332] cpuidle: using governor ladder
[    0.135350] cpuidle: using governor menu
[    0.203282] edma 49000000.edma: TI EDMA DMA engine driver
[    0.207890] SCSI subsystem initialized
[    0.221875] usbcore: registered new interface driver usbfs
[    0.221935] usbcore: registered new interface driver hub
[    0.222003] usbcore: registered new device driver usb
[    0.222723] pps_core: LinuxPPS API ver. 1 registered
[    0.222737] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.222761] PTP clock support registered
[    0.222989] Advanced Linux Sound Architecture Driver Initialized.
[    0.223088] workqueue: max_active 576 requested for napi_workq is out of range, clamping between 1 and 512
[    0.227858] clocksource: Switched to clocksource timer1
[    0.228141] VFS: Disk quotas dquot_6.6.0
[    0.228221] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.232686] thermal_sys: Registered thermal governor 'fair_share'
[    0.232696] thermal_sys: Registered thermal governor 'step_wise'
[    0.232712] thermal_sys: Registered thermal governor 'user_space'
[    0.233263] NET: Registered protocol family 2
[    0.233476] IP idents hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    0.234108] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 6144 bytes, linear)
[    0.234140] TCP established hash table entries: 4096 (order: 2, 16384 bytes, linear)
[    0.234183] TCP bind hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    0.234242] TCP: Hash tables configured (established 4096 bind 4096)
[    0.234342] UDP hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.234365] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.234563] NET: Registered protocol family 1
[    0.243611] RPC: Registered named UNIX socket transport module.
[    0.243633] RPC: Registered udp transport module.
[    0.243639] RPC: Registered tcp transport module.
[    0.243646] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.245787] workingset: timestamp_bits=14 max_order=17 bucket_order=3
[    0.256470] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.258013] NFS: Registering the id_resolver key type
[    0.258058] Key type id_resolver registered
[    0.258066] Key type id_legacy registered
[    0.258115] jffs2: version 2.2 (NAND) (SUMMARY) (LZO) (LZMA) (RTIME) (RUBIN) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.299136] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 248)
[    0.303451] OMAP GPIO hardware version 0.1
[    0.339322] pinctrl-single 44e10800.pinmux: 142 pins, size 568
[    0.342454] Serial: 8250/16550 driver, 16 ports, IRQ sharing enabled
[    0.345384] omap_uart 44e09000.serial: no wakeirq for uart0
[    0.345463] 44e09000.serial: ttyO0 at MMIO 0x44e09000 (irq = 29, base_baud = 3000000) is a OMAP UART0
[    0.964738] printk: console [ttyO0] enabled
[    0.986029] brd: module loaded
[    0.993195] loop: module loaded
[    0.997675] Loading iSCSI transport class v2.0-870.
[    1.010185] mtdoops: mtd device (mtddev=name/number) must be supplied
[    1.018994] libphy: Fixed MDIO Bus: probed
[    1.077791] davinci_mdio 4a101000.mdio: davinci mdio revision 1.6, bus freq 1000000
[    1.085841] libphy: 4a101000.mdio: probed
[    1.091537] davinci_mdio 4a101000.mdio: phy[0]: device 4a101000.mdio:00, driver SMSC LAN8710/LAN8720
[    1.101297] cpsw 4a100000.ethernet: initialized cpsw ale version 1.4
[    1.107985] cpsw 4a100000.ethernet: ALE Table size 1024
[    1.113959] cpsw 4a100000.ethernet: cpts: overflow check period 500 (jiffies)
[    1.121562] cpsw 4a100000.ethernet: Detected MACID = 68:9e:19:6f:3b:66
[    1.130803] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    1.137654] ehci-omap: OMAP-EHCI Host Controller driver
[    1.146028] am335x-phy-driver 47401300.usb-phy: 47401300.usb-phy supply vcc not found, using dummy regulator
[    1.164268] am335x-phy-driver 47401b00.usb-phy: 47401b00.usb-phy supply vcc not found, using dummy regulator
[    1.184722] omap_rtc 44e3e000.rtc: already running
[    1.190626] omap_rtc 44e3e000.rtc: registered as rtc0
[    1.196624] i2c /dev entries driver
[    1.201910] omap_wdt: OMAP Watchdog Timer Rev 0x01: initial timeout 60 sec
[    1.211991] omap_gpio 44e07000.gpio: Could not set line 6 debounce to 200000 microseconds (-22)
[    1.221201] omap_hsmmc 48060000.mmc: Got CD GPIO
[    1.276989] omap_hsmmc 47810000.mmc: RX DMA channel request failed
[    1.287320] ledtrig-cpu: registered to indicate activity on CPUs
[    1.294241] omap-aes 53500000.aes: OMAP AES hw accel rev: 3.2
[    1.300696] omap-aes 53500000.aes: will run requests pump with realtime priority
[    1.310731] omap-sham 53100000.sham: hw accel on OMAP rev 4.3
[    1.323767] davinci-mcasp 48038000.mcasp: IRQ common not found
[    1.336953] NET: Registered protocol family 10
[    1.345184] Segment Routing with IPv6
[    1.349288] NET: Registered protocol family 17
[    1.353967] NET: Registered protocol family 15
[    1.358781] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
[    1.372433] 8021q: 802.1Q VLAN Support v1.8
[    1.376857] Key type dns_resolver registered
[    1.381445] ThumbEE CPU extension supported.
[    1.385921] Registering SWP/SWPB emulation handler
[    1.390961] omap_voltage_late_init: Voltage driver support not added
[    1.397622] sr_dev_init: Unknown instance smartreflex0
[    1.403350] SmartReflex Class3 initialized
[    1.408519] mmc0: host does not support reading read-only switch, assuming write-enable
[    1.417558] mmc0: new SDHC card at address e624
[    1.442158] mmcblk0: mmc0:e624 SU08G 7.40 GiB 
[    1.451918]  mmcblk0: p1 p2
[    1.470747] random: fast init done
[    1.484958] tps65217 0-0024: TPS65217 ID 0xe version 1.2
[    1.491194] omap_i2c 44e0b000.i2c: bus 0 rev0.11 at 400 kHz
[    1.499761] omap_i2c 4819c000.i2c: bus 2 rev0.11 at 100 kHz
[    1.506130] 8<--- cut here ---
[    1.509485] Unable to handle kernel NULL pointer dereference at virtual address 00000008
[    1.517984] pgd = (ptrval)
[    1.520814] [00000008] *pgd=00000000
[    1.524565] Internal error: Oops: 5 [#1] SMP ARM
[    1.529394] Modules linked in:
[    1.532597] CPU: 0 PID: 1108 Comm: kworker/0:3 Not tainted 5.4.154 #0
[    1.539335] Hardware name: Generic AM33XX (Flattened Device Tree)
[    1.545720] Workqueue: events 0xc05aba90
[    1.549822] PC is at 0xc06b4294
[    1.553104] LR is at 0xc06a4968
[    1.556388] pc : [<c06b4294>]    lr : [<c06a4968>]    psr: a0000013
[    1.562944] sp : dd9edd88  ip : 00000002  fp : ffffe000
[    1.568410] r10: c0c96ec4  r9 : c0c04f08  r8 : ddace400
[    1.573875] r7 : 00000000  r6 : de035040  r5 : ddace410  r4 : de034040
[    1.580705] r3 : ddace210  r2 : c09ed4a0  r1 : 00000200  r0 : ddace200
[    1.587537] Flags: NzCv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment none
[    1.595004] Control: 10c5387d  Table: 80004019  DAC: 00000051
[    1.601016] Process kworker/0:3 (pid: 1108, stack limit = 0x(ptrval))
[    1.607757] Stack: (0xdd9edd88 to 0xdd9ee000)
[    1.612319] dd80:                   c0c04f08 c06831fc de034040 c0c96ec0 de035040 c0c96ebc
[    1.620881] dda0: ddace400 c06a4968 00000a20 00000000 c0c971f4 dfdeea38 a0000013 ddace410
[    1.629443] ddc0: dd96fa40 00000038 c0c96ec0 c0c96eb8 00000000 c04fb214 00000000 dfdee528
[    1.638006] dde0: 00000000 00000001 00000001 c071214c ddbbe900 ddbbe900 c0c271f8 c02d48d0
[    1.646570] de00: ddbbe900 00000000 00000000 c0a35c48 00000001 c02d4a7c c0c3fbc0 00000006
[    1.655134] de20: ddaac360 c02d46fc 00000000 ddbbe900 ddacc600 ddacc600 ddbbe900 0ebe159f
[    1.663696] de40: c0a35c48 ddace410 00000000 c0c3fbc0 00000000 00000000 c0c3fbc0 00000006
[    1.672261] de60: ffffe000 c05adf3c c0c9482c ddace410 c0c94824 00000000 00000000 c05ac51c
[    1.680825] de80: ddace410 c0c3fbc0 c05ac9b0 00000001 00000000 00000000 00000000 c05ac800
[    1.689387] dea0: c0c3fbc0 dd9edee8 ddace410 00000000 dd9edee8 c05ac9b0 00000001 00000000
[    1.697948] dec0: 00000000 00000000 ffffe000 c05aaa54 de008b6c de35b6b8 ddace410 ddace454
[    1.706512] dee0: c0c37cd0 c05ac2b4 ddace410 00000001 c0c37a54 ddace410 ddace410 c0c37cd0
[    1.715074] df00: dfdc5c00 c05ab668 ddace410 c0c37a4c c0c37a54 c05abaf8 c0c37aa0 dd922500
[    1.723636] df20: dfdc29c0 c0145dd0 00000008 c0c03d00 dd922500 dd922514 dfdc29c0 00000008
[    1.732197] df40: c0c03d00 dfdc29d8 dfdc29c0 c01462d4 c0c1de30 c092f0fc ffffe000 dd922500
[    1.740759] df60: c014602c de3dec00 de3ded00 00000000 dd9ec000 dd922500 c014602c de071eac
[    1.749323] df80: de3dec1c c014b7c0 00000015 de3ded00 c014b674 00000000 00000000 00000000
[    1.757886] dfa0: 00000000 00000000 00000000 c01010e8 00000000 00000000 00000000 00000000
[    1.766448] dfc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[    1.775009] dfe0: 00000000 00000000 00000000 00000000 00000013 00000000 00000000 00000000
[    1.783580] Function entered at [<c06b4294>] from [<c06a4968>]
[    1.789684] Function entered at [<c06a4968>] from [<c05adf3c>]
[    1.795786] Function entered at [<c05adf3c>] from [<c05ac51c>]
[    1.801889] Function entered at [<c05ac51c>] from [<c05ac800>]
[    1.807991] Function entered at [<c05ac800>] from [<c05aaa54>]
[    1.814092] Function entered at [<c05aaa54>] from [<c05ac2b4>]
[    1.820194] Function entered at [<c05ac2b4>] from [<c05ab668>]
[    1.826296] Function entered at [<c05ab668>] from [<c05abaf8>]
[    1.832397] Function entered at [<c05abaf8>] from [<c0145dd0>]
[    1.838500] Function entered at [<c0145dd0>] from [<c01462d4>]
[    1.844601] Function entered at [<c01462d4>] from [<c014b7c0>]
[    1.850705] Function entered at [<c014b7c0>] from [<c01010e8>]
[    1.856807] Exception stack(0xdd9edfb0 to 0xdd9edff8)
[    1.862093] dfa0:                                     00000000 00000000 00000000 00000000
[    1.870654] dfc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[    1.879213] dfe0: 00000000 00000000 00000000 00000000 00000013 00000000
[    1.886140] Code: e34c209e e5953024 e2430010 e5937040 (e5978008) 
[    1.892559] ---[ end trace b1ea14783d63706c ]---
[    1.897394] Kernel panic - not syncing: Fatal exception
[    1.902870] Rebooting in 1 seconds..
```

</details>

**Comment by alexeys85** [comment] 2022-02-10 07:32
Have you tried to boot from internal eMMC?

**Comment by ynezz** [comment] 2022-02-10 09:18
> Unable to handle kernel NULL pointer dereference at virtual
 > address 00000008
Nice one. Are you able to reproduce with current development snapshot?

 > PC is at 0xc06b4294
 > LR is at 0xc06a4968

Resolving those addresses to source code locations would help tracking 
down the issue.

**Comment by efx** [comment] 2022-02-11 20:01
> Have you tried to boot from internal eMMC?

Good question; I have not. This was only from the sdcard.

> Nice one. Are you able to reproduce with current development snapshot?

I shall give that a whirl and report back!

**Comment by ynezz** [comment] 2022-02-12 09:01
> PC is at 0xc06b4294

0xc06b4294 is in dsps_musb_init (drivers/usb/musb/musb_dsps.c:430)

> LR is at 0xc06a4968

0xc06a4968 is in musb_probe (drivers/usb/musb/musb_core.c:2217)

**Comment by ynezz** [comment] 2022-02-12 09:20
Looks like it should be fixed in 
https://github.com/torvalds/linux/commit/9ab5d539bc975b8dcde86eca1b58d836b657732e 
which was first fixed in 5.4.155, so should be fixed in the next 21.02.2 
release. In order to confirm that, try to use 
[21.02-SNAPSHOT](https://downloads.openwrt.org/releases/21.02-SNAPSHOT/targets/omap/generic/) 
and report back.

**Comment by efx** [comment] 2022-02-12 17:29
@ynezz wow, precise diagnosis and clear instructions! 
I will try that snapshot this week and report back.

**Comment by ynezz** [comment] 2022-02-21 13:30
21.02.2 is out, try to reproduce and if it's not fixed, then report back and I'll reopen this.

**Closed by ynezz** 2022-02-21 13:30 UTC
Labels: kernel, release/21.02
