### ISSUE TITLE
daemon.err hostapd: 160 MHz channel width is not supported in 5 / 6GHz

### ISSUE THREAD

**Issue by starraiderx** [openwrt/openwrt#12253] opened 2023-03-23 16:18 UTC
### Describe the bug

Setting htmode to HE160 doesn't work and produces the following syslog error: `"daemon.err hostapd: 160 MHz channel width is not supported in 5 / 6GHz."` The router used to support HE160 on previous Snapshot Builds.

### OpenWrt version

r22371-0eebc6f0dd

### OpenWrt target/subtarget

ipq807x/generic

### Device

Xiaomi AX3600

### Image kind

Official downloaded image

### Steps to reproduce

Flash image from https://downloads.openwrt.org/snapshots/targets/ipq807x/generic/

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by abajk** [comment] 2023-03-23 19:41
I think the problem is specific to the Qualcomm radios. Yesterday I have been building a snapshot image on Netgear WAX206 (Mediatek Soc) and HE160 works fine.

**Comment by tmtom** [comment] 2023-03-25 10:09
I can confirm the same, on my Xiaomi AX3600, on build r22297-1781e7408a 160MHz channel worked and on r22371-0eebc6f0dd does not work any more.

**Comment by tmtom** [comment] 2023-03-28 09:47
> 

Yes, seems to be an ath11k issue, perhaps 789a0bac35359a3958da0e555231c5bf28abf7c4 ?

**Comment by Soromeister** [comment] 2023-04-01 22:41
Confirmed fixed in build `r22475-936df715de`

**Comment by Djfe** [comment] 2023-07-14 10:44
@starraiderx pls close

**Closed** 2023-07-14 10:44 UTC
Labels: bug
