### ISSUE TITLE
Netifd Segmentation Error when Adding Large Number of Interfaces

### ISSUE THREAD

**Issue by shripadrayewar** [openwrt/openwrt#12393] opened 2023-04-14 15:28 UTC
### Describe the bug

Hi
I am encountering an issue with OpenWRT's netifd when attempting to add 40 or more interfaces to my network configuration file. Upon adding the interfaces, netifd gives a segmentation error in dmesg, and the interfaces do not show up with the ip a command. However, the interface configurations are present in the network configuration file.
Follwing is the error im getting while network restart on dmesg

`[ 7400.201808] netifd[22825]: segfault at a0 ip 08057fdc sp bfe16fd0 error 4 in netifd[804b000+1c000]
[ 7400.212899] Code: 8d 65 f4 5b 5e 5f 5d e9 f7 fd ff ff 8d 65 f4 5b 5e 5f 5d c3 80 78 0c 00 0f 84 98 00 00 00 55 89 e5 53 51 8b 58 1c c6 40 0c 00 <8b> 83 a0 00 00 00 48 89 83 a0 00 00 00 f6 05 ac 38 07 08 02 74 2c
[ 7407.152861] netifd[23845]: segfault at a0 ip 08057fdc sp bfb553e0 error 4 in netifd[804b000+1c000]
[ 7407.163195] Code: 8d 65 f4 5b 5e 5f 5d e9 f7 fd ff ff 8d 65 f4 5b 5e 5f 5d c3 80 78 0c 00 0f 84 98 00 00 00 55 89 e5 53 51 8b 58 1c c6 40 0c 00 <8b> 83 a0 00 00 00 48 89 83 a0 00 00 00 f6 05 ac 38 07 08 02 74 2c
[ 7414.155714] netifd[25731]: segfault at a0 ip 08057fdc sp bfba09e0 error 4 in netifd[804b000+1c000]
[ 7414.165320] Code: 8d 65 f4 5b 5e 5f 5d e9 f7 fd ff ff 8d 65 f4 5b 5e 5f 5d c3 80 78 0c 00 0f 84 98 00 00 00 55 89 e5 53 51 8b 58 1c c6 40 0c 00 <8b> 83 a0 00 00 00 48 89 83 a0 00 00 00 f6 05 ac 38 07 08 02 74 2c
[ 7421.032886] netifd[26965]: segfault at a0 ip 08057fdc sp bfa6cd90 error 4 in netifd[804b000+1c000]
[ 7421.043189] Code: 8d 65 f4 5b 5e 5f 5d e9 f7 fd ff ff 8d 65 f4 5b 5e 5f 5d c3 80 78 0c 00 0f 84 98 00 00 00 55 89 e5 53 51 8b 58 1c c6 40 0c 00 <8b> 83 a0 00 00 00 48 89 83 a0 00 00 00 f6 05 ac 38 07 08 02 74 2c
`

Follwoing is my configuration

`
config interface 'loopback'
	option device 'lo'
	option proto 'static'
	list ipaddr '127.0.0.1/8'

config globals 'globals'
	option ula_prefix 'fd3c:3439:836a::/48'

config interface 'wan'
	option device 'eth0'
	option proto 'static'
	option ipaddr '192.168.1.20'
	option netmask '255.255.255.0'
	option gateway '192.168.1.200'
	list dns '8.8.8.8'
	option metric '1'

config interface 'wg_mgmnt'
	option proto 'wireguard'
	list addresses '10.50.1.37/32'
	option private_key '#################################'

config wireguard_wg_mgmnt
	option persistent_keepalive '25'
	option public_key '########################'
	option description 'Management VPN'
	option endpoint_port '54321'
	option endpoint_host '##########'
	list allowed_ips '10.50.0.1'
	list allowed_ips ''
	option preshared_key '######################'
	option route_allowed_ips '1'

config interface 'loopback_ipsec'
	option proto 'static'
	option device 'lo'
	option ipaddr '10.220.220.1'
	option netmask '255.255.255.255'

config interface 'VXLAN_Kankavali'
	option proto 'vxlan'
	option peeraddr '10.220.220.3'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '3'

config interface 'VXL_Kanka_IP'
	option proto 'static'
	option device 'VXLAN_Kankavali'
	option ipaddr '172.16.16.1'
	option netmask '255.255.255.252'

config interface 'VXLAN_JALNA'
	option proto 'vxlan'
	option peeraddr '10.220.220.4'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '4'

config interface 'VXL_JALNA_IP'
	option proto 'static'
	option device 'VXLAN_JALNA'
	option ipaddr '172.16.16.5'
	option netmask '255.255.255.252'

config interface 'VXLAN_PARBHANI'
	option proto 'vxlan'
	option peeraddr '10.220.220.5'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '5'

config interface 'VXL_PARBHANI_IP'
	option proto 'static'
	option device 'VXLAN_PARBHANI'
	option ipaddr '172.16.16.9'
	option netmask '255.255.255.252'

config interface 'VXLAN_LATUR'
	option proto 'vxlan'
	option peeraddr '10.220.220.6'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '6'

config interface 'VXL_LATUR_IP'
	option proto 'static'
	option device 'VXLAN_LATUR'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.13'

config interface 'VXLAN_USMANABAD'
	option proto 'vxlan'
	option peeraddr '10.220.220.7'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '7'

config interface 'VXL_USMANABAD_IP'
	option proto 'static'
	option device 'VXLAN_USMANABAD'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.17'

config interface 'VXLAN_SOLAPUR'
	option proto 'vxlan'
	option peeraddr '10.220.220.8'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '8'

config interface 'VXL_SOLAPUR_IP'
	option proto 'static'
	option device 'VXLAN_SOLAPUR'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.21'

config interface 'VXLAN_YEOTMAL'
	option proto 'vxlan'
	option peeraddr '10.220.220.9'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '9'

config interface 'VXL_YEOTMAL_IP'
	option proto 'static'
	option device 'VXLAN_YEOTMAL'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.25'

config interface 'VXLAN_MALEGAON'
	option proto 'vxlan'
	option peeraddr '10.220.220.10'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '10'

config interface 'VXL_MALEGAON_IP'
	option proto 'static'
	option device 'VXLAN_MALEGAON'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.29'

config interface 'VXLAN_JALGAON'
	option proto 'vxlan'
	option peeraddr '10.220.220.11'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '11'

config interface 'VXL_JALGAON_IP'
	option proto 'static'
	option device 'VXLAN_JALGAON'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.33'

config interface 'VXLAN_BHUSAWAL'
	option proto 'vxlan'
	option ipaddr '10.220.220.1'
	option port '8472'
	option peeraddr '10.220.220.13'
	option vid '13'

config interface 'VXL_BHUSAWAL_IP'
	option proto 'static'
	option device 'VXLAN_BHUSAWAL'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.41'

config interface 'VXLAN_PEN'
	option proto 'vxlan'
	option peeraddr '10.220.220.14'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '14'

config interface 'VXL_PEN_IP'
	option proto 'static'
	option device 'VXLAN_PEN'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.45'

config interface 'VXLAN_CHIPLUN'
	option proto 'vxlan'
	option peeraddr '10.220.220.15'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '15'

config interface 'VXL_CHIPLUN_IP'
	option proto 'static'
	option device 'VXLAN_CHIPLUN'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.49'

config interface 'VXLAN_RATNAGIRI'
	option proto 'vxlan'
	option peeraddr '10.220.220.16'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '16'

config interface 'VXL_RATNAGIRI_IP'
	option proto 'static'
	option device 'VXLAN_RATNAGIRI'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.53'

config interface 'VXLAN_SANGLI'
	option proto 'vxlan'
	option peeraddr '10.220.220.17'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '17'
	option auto '0'

config interface 'VXL_SANGLI_IP'
	option proto 'static'
	option device 'VXLAN_SANGLI'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.57'
	option auto '0'

config interface 'VXLAN_SHIVAJINAGAR'
	option proto 'vxlan'
	option peeraddr '10.220.220.18'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '18'

config interface 'VXL_SHIVAJINAGAR_IP'
	option proto 'static'
	option device 'VXLAN_SHIVAJINAGAR'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.61'

config interface 'VXLAN_DAPODI'
	option proto 'vxlan'
	option peeraddr '10.220.220.19'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '19'

config interface 'VXL_DAPODI_IP'
	option proto 'static'
	option device 'VXLAN_DAPODI'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.65'

config interface 'VXLAN_AURANGABAD'
	option proto 'vxlan'
	option peeraddr '10.220.220.20'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '20'

config interface 'VXL_AURANGABAD_IP'
	option proto 'static'
	option device 'VXLAN_AURANGABAD'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.69'

config interface 'VXLAN_BEED'
	option proto 'vxlan'
	option peeraddr '10.220.220.21'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '21'

config interface 'VXL_BEED_IP'
	option proto 'static'
	option device 'VXLAN_BEED'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.73'

config interface 'VXLAN_NANDED'
	option proto 'vxlan'
	option peeraddr '10.220.220.22'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '22'

config interface 'VXL_NANDED_IP'
	option proto 'static'
	option device 'VXLAN_NANDED'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.77'

config interface 'VXLAN_NASHIK'
	option proto 'vxlan'
	option peeraddr '10.220.220.23'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '23'

config interface 'VXL_NASHIK_IP'
	option proto 'static'
	option device 'VXLAN_NASHIK'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.81'

config interface 'VXLAN_PANCHAVATI'
	option proto 'vxlan'
	option peeraddr '10.220.220.24'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '24'

config interface 'VXL_PANCHAVATI_IP'
	option proto 'static'
	option device 'VXLAN_PANCHAVATI'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.85'

config interface 'VXLAN_AKOLA'
	option proto 'vxlan'
	option peeraddr '10.220.220.25'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '25'

config interface 'VXL_AKOLA_IP'
	option proto 'static'
	option netmask '255.255.255.252'
	option device 'VXLAN_AKOLA_EXT'
	option ipaddr '172.16.16.217'

config interface 'VXLAN_BULDHANA'
	option proto 'vxlan'
	option peeraddr '10.220.220.26'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '26'

config interface 'VXL_BULDHANA_IP'
	option proto 'static'
	option device 'VXLAN_BULDHANA'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.93'

config interface 'VXLAN_AMRAVATI'
	option proto 'vxlan'
	option peeraddr '10.220.220.27'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '27'

config interface 'VXL_AMRAVATI_IP'
	option proto 'static'
	option device 'VXLAN_AMRAVATI'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.97'

config interface 'VXLAN_WARDHA'
	option proto 'vxlan'
	option peeraddr '10.220.220.28'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '28'

config interface 'VXL_WARDHA_IP'
	option proto 'static'
	option device 'VXLAN_WARDHA'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.101'

config interface 'VXLAN_NAGPUR'
	option proto 'vxlan'
	option peeraddr '10.220.220.29'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '29'

config interface 'VXL_NAGPUR_IP'
	option proto 'static'
	option device 'VXLAN_NAGPUR'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.105'

config interface 'VXLAN_BHANDARA'
	option proto 'vxlan'
	option peeraddr '10.220.220.30'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '30'

config interface 'VXL_BHANDARA_IP'
	option proto 'static'
	option device 'VXLAN_BHANDARA'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.109'

config interface 'VXLAN_CHANDRAPUR'
	option proto 'vxlan'
	option peeraddr '10.220.220.31'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '31'

config interface 'VXL_CHANDRAPUR_IP'
	option proto 'static'
	option device 'VXLAN_CHANDRAPUR'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.113'

config interface 'VXLAN_SATARA'
	option proto 'vxlan'
	option peeraddr '10.220.220.32'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '32'

config interface 'VXL_SATARA_IP'
	option proto 'static'
	option device 'VXLAN_SATARA'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.117'

config interface 'VXLAN_PANDHARPUR'
	option proto 'vxlan'
	option peeraddr '10.220.220.33'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '33'

config interface

config interface 'VXL_PANDHARPUR_IP'
	option proto 'static'
	option device 'VXLAN_PANDHARPUR'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.121'

config interface 'VXLAN_THANE'
	option proto 'vxlan'
	option peeraddr '10.220.220.34'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '34'

config interface 'VXL_THANE_IP'
	option proto 'static'
	option device 'VXLAN_THANE'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.125'

config interface 'VXLAN_DIVISIONAL_OFFICE_PUNE'
	option proto 'vxlan'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '35'
	option peeraddr '10.220.220.35'

config interface 'VXL_DIVISIONAL_OFFICE_PUNE_IP'
	option proto 'static'
	option device 'VXLAN_DIVISIONAL_OFFICE_PUNE'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.129'

config interface 'VXLAN_AHMEDNAGAR'
	option proto 'vxlan'
	option peeraddr '10.220.220.36'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '36'

config interface 'VXL_AHMEDNAGAR_IP'
	option proto 'static'
	option device 'VXLAN_AHMEDNAGAR'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.133'

config interface 'VXLAN_KOLHAPUR'
	option proto 'vxlan'
	option peeraddr '10.220.220.37'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '37'

config interface 'VXL_KOLHAPUR_IP'
	option proto 'static'
	option device 'VXLAN_KOLHAPUR'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.137'

config interface 'VXLAN_KALYAN'
	option proto 'vxlan'
	option peeraddr '10.220.220.38'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '38'

config interface 'VXL_KALYAN_IP'
	option proto 'static'
	option device 'VXLAN_KALYAN'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.141'

config interface 'VXLAN_PUSAD'
	option proto 'vxlan'
	option peeraddr '10.220.220.39'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '39'

config interface 'VXL_PUSAD_IP'
	option proto 'static'
	option device 'VXLAN_PUSAD'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.145'

config interface 'VXLAN_KARAD'
	option proto 'vxlan'
	option peeraddr '10.220.220.40'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '40'

config interface 'VXL_KARAD_IP'
	option proto 'static'
	option device 'VXLAN_KARAD'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.149'

config interface 'VXLAN_BARAMATI'
	option proto 'vxlan'
	option peeraddr '10.220.220.41'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '41'

config interface 'VXL_BARAMATI_IP'
	option proto 'static'
	option device 'VXLAN_BARAMATI'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.153'

config interface 'VXLAN_SHRIRAMPUR'
	option proto 'vxlan'
	option peeraddr '10.220.220.42'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '42'

config interface 'VXL_SHRIRAMPUR_IP'
	option proto 'static'
	option device 'VXLAN_SHRIRAMPUR'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.157'

config interface 'VXLAN_KURLA'
	option proto 'vxlan'
	option peeraddr '10.220.220.43'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '43'

config interface 'VXL_KURLA_IP'
	option proto 'static'
	option device 'VXLAN_KURLA'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.161'

config interface 'VXLAN_GADHINGLAJ'
	option proto 'vxlan'
	option peeraddr '10.220.220.44'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '44'

config interface 'VXL_GADHINGLAJ_IP'
	option proto 'static'
	option device 'VXLAN_GADHINGLAJ'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.165'

config interface 'VXLAN_DHULE'
	option proto 'vxlan'
	option peeraddr '10.220.220.45'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '45'

config interface 'VXL_DHULE_IP'
	option proto 'static'
	option device 'VXLAN_DHULE'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.169'

config interface 'VXLAN_CHIKHALTHANA'
	option proto 'vxlan'
	option peeraddr '10.220.220.46'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '46'

config interface 'VXL_CHIKHALTHANA_IP'
	option proto 'static'
	option device 'VXLAN_CHIKHALTHANA'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.173'

config interface 'VXLAN_VASAI'
	option proto 'vxlan'
	option peeraddr '10.220.220.47'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '47'

config interface 'VXL_VASAI_IP'
	option proto 'static'
	option device 'VXLAN_VASAI'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.177'

config interface 'VXLAN_NANDURBAR'
	option proto 'vxlan'
	option peeraddr '10.220.220.48'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '48'

config interface 'VXL_NANDURBAR_IP'
	option proto 'static'
	option device 'VXLAN_NANDURBAR'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.181'

config interface 'VXLAN_MIRAJ'
	option proto 'vxlan'
	option peeraddr '10.220.220.49'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '49'

config interface 'VXL_MIRAJ_IP'
	option proto 'static'
	option device 'VXLAN_MIRAJ'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.185'

config interface 'VXLAN_KHAMGAON'
	option proto 'vxlan'
	option peeraddr '10.220.220.50'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '50'

config interface 'VXL_KHAMGAON_IP'
	option proto 'static'
	option device 'VXLAN_KHAMGAON'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.189'

config interface 'VXLAN_PALGHAR'
	option proto 'vxlan'
	option peeraddr '10.220.220.51'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '51'

config interface 'VXL_PALGHAR_IP'
	option proto 'static'
	option device 'VXLAN_PALGHAR'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.193'

config interface 'VXLAN_HINGNA'
	option proto 'vxlan'
	option peeraddr '10.220.220.52'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '52'

config interface 'VXL_HINGNA_IP'
	option proto 'static'
	option device 'VXLAN_HINGNA'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.197'

config interface 'VXLAN_AHMEDNAGAR_EXT'
	option proto 'vxlan'
	option peeraddr '10.220.220.53'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '53'

config interface 'VXL_AHMEDNAGAR_EXT_IP'
	option proto 'static'
	option device 'VXLAN_AHMEDNAGAR_EXT'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.201'

config interface 'VXLAN_NASHIK_EXT'
	option proto 'vxlan'
	option peeraddr '10.220.220.54'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '54'

config interface 'VXL_NASHIK_EXT_IP'
	option proto 'static'
	option device 'VXLAN_NASHIK_EXT'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.205'

config interface 'VXLAN_KURLA_NEHARUNAGAR'
	option proto 'vxlan'
	option peeraddr '10.220.220.55'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '55'

config interface 'VXL_KURLA_NEHARUNAGAR_IP'
	option proto 'static'
	option device 'VXLAN_KURLA_NEHARUNAGAR'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.209'

config interface 'VXLAN_PARBHANI_EXT'
	option proto 'vxlan'
	option peeraddr '10.220.220.56'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '56'

config interface 'VXL_PARBHANI_EXT_IP'
	option proto 'static'
	option device 'VXLAN_PARBHANI_EXT'
	option netmask '255.255.255.252'
	option ipaddr '172.16.16.213'

config interface 'VXLAN_AKOLA_EXT'
	option proto 'vxlan'
	option peeraddr '10.220.220.57'
	option ipaddr '10.220.220.1'
	option port '8472'
	option vid '57'

`

### OpenWrt version

r0-f7c460685b

### OpenWrt target/subtarget

ramips/mt7621

### Device

PBR-M1

### Image kind

Self-built image

### Steps to reproduce

just load network config

### Actual behaviour

netifd unable to create interfaces and segmentaion fault

### Expected behaviour

it should create interfaces

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

@nbd168

**Comment by shripadrayewar** [comment] 2023-04-15 10:41
any one??

**Comment by shripadrayewar** [comment] 2023-04-15 10:42
any one

**Comment by nbd168** [comment] 2023-04-15 13:33
Please give me some more details on what version you are using. I can't find any info on r0-f7c460685b. I also can't reproduce the issue myself with your config

**Comment by shripadrayewar** [comment] 2023-04-15 16:05
i tried multiple versions including on couple platforms like mipsbe and x86.
X86 - 
NAME="OpenWrt"
VERSION="21.02-SNAPSHOT"
ID="openwrt"
ID_LIKE="lede openwrt"
PRETTY_NAME="OpenWrt 21.02-SNAPSHOT"
VERSION_ID="21.02-snapshot"
HOME_URL="https://openwrt.org/"
BUG_URL="https://bugs.openwrt.org/"
SUPPORT_URL="https://forum.openwrt.org/"
BUILD_ID="r0-6499f973"
OPENWRT_BOARD="x86/generic"
OPENWRT_ARCH="i386_pentium4"
OPENWRT_TAINTS="no-all"
OPENWRT_DEVICE_MANUFACTURER="OpenWrt"
OPENWRT_DEVICE_MANUFACTURER_URL="https://openwrt.org/"
OPENWRT_DEVICE_PRODUCT="Generic"
OPENWRT_DEVICE_REVISION="v0"
OPENWRT_RELEASE="OpenWrt 21.02-SNAPSHOT r0-6499f973"

MIPS:-
NAME="OpenWrt"
VERSION="21.02-SNAPSHOT"
ID="openwrt"
ID_LIKE="lede openwrt"
PRETTY_NAME="OpenWrt 21.02-SNAPSHOT"
VERSION_ID="21.02-snapshot"
HOME_URL="https://openwrt.org/"
BUG_URL="https://bugs.openwrt.org/"
SUPPORT_URL="https://forum.openwrt.org/"
BUILD_ID="r0-0d716ad8"
OPENWRT_BOARD="ramips/mt7621"
OPENWRT_ARCH="mipsel_24kc"
OPENWRT_TAINTS="no-all"
OPENWRT_DEVICE_MANUFACTURER="OpenWrt"
OPENWRT_DEVICE_MANUFACTURER_URL="https://openwrt.org/"
OPENWRT_DEVICE_PRODUCT="Generic"
OPENWRT_DEVICE_REVISION="v0"
OPENWRT_RELEASE="OpenWrt 21.02-SNAPSHOT r0-0d716ad8"

**Comment by nbd168** [comment] 2023-04-15 16:30
Can you please try a recent version, either 22.03 or master snapshot?

**Comment by shripadrayewar** [comment] 2023-04-15 16:54
tried on 22.03. same issue
![image](https://user-images.githubusercontent.com/125957854/232239152-298001d0-2e50-4e5a-9581-22f00b0bb1dd.png)

![image](https://user-images.githubusercontent.com/125957854/232239188-c71cbe7f-d55b-422b-b64b-5e662a42fdbc.png)

**Comment by brada4** [comment] 2023-04-15 19:35
What does ifconfig show,i.e how far file gets parsed succesfully (conf file itself looks sane)

**Comment by nbd168** [comment] 2023-04-15 20:20
I managed to reproduce it now. Will work on a fix

**Comment by shripadrayewar** [comment] 2023-04-16 06:44
> What does ifconfig show,i.e how far file gets parsed succesfully (conf file itself looks sane)

ifconfig only shows some random  interfaces from the file.

**Comment by nbd168** [comment] 2023-04-17 11:15
I pushed a fix to OpenWrt master. With that fix, it no longer crashes in my tests with your config.

**Closed** 2023-04-18 15:06 UTC
Labels: bug
