### ISSUE TITLE
Severe WAN performance degradation when Fast Ethernet devices are connected to a Gigabit switch and transfer data over LAN (probably present on most OpenWrt versions)

### ISSUE THREAD

**Issue by sppmasterspp** [openwrt/openwrt#9985] opened 2022-06-03 12:32 UTC
I found out a new unpleasant issue. WAN slowdown issue (bug) when there is simultaneous LAN traffic between 1Gbps device and 100Mbps device.
Summary of the problem - When a 100Mbps client/s (Fast Ethernet) is/are connected to a router gigabit switch and there is a LAN data transfer between a Gigabit device (desktop PC in my case) and at least one 100Mbps device, the desktop PC (gigabit device) can only download/upload to WAN at really low speeds. The WAN performance drop to just 20-30Mbps download/upload speed with huge ping times.

All details are given in several threads on the forum.openwrt.org
https://forum.openwrt.org/t/ipq806x-nss-build-netgear-r7800-tp-link-c2600-linksys-ea8500/82525/1877?u=sppmaster

I've tried this with several gigabit routers - Netgear R7800, TP-Link WDR4300, Belkin RT3200. With all of them the results are completely repeatable using the same bench test setup.
I've tried several OpenWRT versions with default and custom configurations. The issue is present on all stock firmwares I've tried too and they are based on older OpenWRT code.

No such loss of performance can be observed when only Gigabit clients are connected to the gigabit switch. Instead we achieve Gigabit Full Duplex speeds as can be expected - simultaneous 1Gbps download and 1Gbps upload WAN/LAN performance no matter of the LAN traffic.

**Comment by Ansuel** [comment] 2022-06-04 13:44
Mhhh this should be a duplicate of #9202.. We should track this there...

**Closed by Ansuel** 2022-06-04 13:44 UTC
